---
namespace: stayturgid
name: firerpa
version: 0.1.0
readme: README.md
authors:
  - stayturgid
description: Ansible collection for FIRERPA/lamda deployment on Android devices
license: MIT
repository: https://github.com/djbclark/stayturgid
tags: [firerpa, lamda, android, failsafe]
