namespace: stayturgid
name: fdroid
version: 1.1.0
readme: README.md
authors:
  - djbclark
description: F-Droid repository management via fdroidcl on the control node.
license:
  - MIT
tags:
  - android
  - fdroid
repository: https://github.com/djbclark/stayturgid
dependencies:
  stayturgid.android_common: ">=1.0.0"
