---
target_device: p7a
stayturgid_repo_root: "{{ playbook_dir }}/../.."

stayturgid_fdroid_repos:
  - name: "IzzyOnDroid"
    address: "https://apt.izzysoft.de/fdroid/repo"
    fingerprint: "3BF0D6ABFEAE2F401707B6D966BE743BF0EEE49C2561B9BA39073711F628937A"
  - name: "Guardian Project"
    address: "https://guardianproject.info/fdroid/repo"
    fingerprint: "B7C2EEFD8DAC7806AF67DFCD92EB18126BC08312A7F2D6F3862E46013C7A6135"

stayturgid_ensure_neo_store: true
stayturgid_push_repos_to_device: true
stayturgid_fdroid_update_index: true

neo_store_package: com.machiav3lli.fdroid

# Optional fdroidcl mass-install definitions:
# stayturgid_fdroid_setups:
#   - name: base-tools
#     repos: ["IzzyOnDroid"]
#     apps:
#       - org.breezyweather
