---
all:
  hosts:
    myphone:
      ansible_host: 192.0.2.50
      ansible_port: 8022
      ansible_user: u0_a123
      ansible_python_interpreter: /data/data/com.termux/files/usr/bin/python
      termux_prefix: /data/data/com.termux/files/usr
      termux_home: /data/data/com.termux/files/home
      stayturgid_sd_root: /sdcard/stayturgid
      stayturgid_obtainium_apps: []   # set or copy from stayturgid group_vars
