#!/usr/bin/env python3
"""Obtain Google Play AAS token via Chrome EmbeddedSetup + apkeep.

The EmbeddedSetup page hangs forever after "I agree" — that is expected.
This script opens the page, waits until Chrome has a fresh oauth_token cookie,
exchanges it with apkeep for a long-lived AAS token, and writes:

  ~/.config/stayturgid/play.env   (GPLAY_EMAIL + GPLAY_AAS_TOKEN)
  ~/.config/apkeep/apkeep.ini     (optional mirror for apkeep -i)

Requires: Chrome, apkeep on PATH, and (once) Keychain access to Chrome cookies.
Deps: pip install browser-cookie3  (or use a venv).
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import time
import webbrowser
from pathlib import Path

EMBEDDED_SETUP = "https://accounts.google.com/EmbeddedSetup"
CONFIG_DIR = Path.home() / ".config" / "stayturgid"
PLAY_ENV = CONFIG_DIR / "play.env"
APKEEP_INI = Path.home() / ".config" / "apkeep" / "apkeep.ini"


def _ensure_browser_cookie3_python() -> None:
    """Re-exec under a venv that has browser-cookie3 if system Python lacks it."""
    try:
        import browser_cookie3  # noqa: F401

        return
    except ImportError:
        pass
    # Only the home-dir venv is checked — a fixed /tmp path here would mean
    # execv()'ing a binary from a predictable, world-writable location (see
    # tmpfile security audit, 2026-07-21).
    py = Path.home() / ".venv-stayturgid-play" / "bin" / "python"
    if py.is_file():
        os.execv(str(py), [str(py), os.path.abspath(__file__), *sys.argv[1:]])
    sys.stderr.write(
        "ERROR: browser-cookie3 not installed. Try:\n"
        "  python3 -m venv ~/.venv-stayturgid-play\n"
        "  ~/.venv-stayturgid-play/bin/pip install browser-cookie3\n"
        "  ~/.venv-stayturgid-play/bin/python %s …\n" % __file__
    )
    raise SystemExit(2)


def read_oauth_cookie():
    import browser_cookie3

    cj = browser_cookie3.chrome(domain_name="accounts.google.com")
    for c in cj:
        if c.name == "oauth_token" and (c.value or "").startswith("oauth2_4/"):
            return c.value
    return None


def exchange_aas(email: str, oauth: str) -> str:
    apkeep = shutil.which("apkeep")
    if not apkeep:
        raise SystemExit("ERROR: apkeep not on PATH (brew install apkeep)")
    # Do not quote the oauth token value in a way that breaks apkeep; pass as argv.
    r = subprocess.run(
        [apkeep, "-e", email, "--oauth-token", oauth],
        capture_output=True,
        text=True,
    )
    out = (r.stdout or "").strip()
    err = (r.stderr or "").strip()
    text = "\n".join(x for x in (out, err) if x)
    # apkeep prints "AAS Token: aas_et/…" (sometimes on stderr).
    import re

    m = re.search(r"(aas_et/[A-Za-z0-9_\-]+)", text)
    if m:
        return m.group(1)
    for line in text.splitlines():
        line = line.strip()
        if line.startswith("aas_et/") or line.startswith("aas_"):
            return line
    if r.returncode == 0 and text and not text.lower().startswith("error"):
        if "\n" not in text and " " not in text:
            return text
    raise RuntimeError(text or ("apkeep failed rc=%s" % r.returncode))


def write_creds(email: str, aas: str) -> None:
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    play = (
        "# Local only — never commit. Generated by obtain_play_aas.py\n"
        "export GPLAY_EMAIL=%r\n"
        "export GPLAY_AAS_TOKEN=%r\n" % (email, aas)
    )
    PLAY_ENV.write_text(play)
    PLAY_ENV.chmod(0o600)

    APKEEP_INI.parent.mkdir(parents=True, exist_ok=True)
    APKEEP_INI.write_text("[google]\nemail = %s\naas_token = %s\n" % (email, aas))
    APKEEP_INI.chmod(0o600)


def main(argv: list[str] | None = None) -> int:
    _ensure_browser_cookie3_python()

    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("-e", "--email", required=True, help="Google Play account email address")
    p.add_argument(
        "--timeout",
        type=int,
        default=300,
        help="seconds to wait for a fresh oauth cookie (default 300)",
    )
    p.add_argument(
        "--poll",
        type=float,
        default=2.0,
        help="seconds between cookie polls",
    )
    p.add_argument(
        "--no-open",
        action="store_true",
        help="do not open the browser (you already have EmbeddedSetup open)",
    )
    p.add_argument(
        "--smoke-test",
        action="store_true",
        help="after success, try apkeep --list-versions on a free app",
    )
    args = p.parse_args(argv)

    baseline = read_oauth_cookie()
    if baseline:
        print(
            "Chrome already has an oauth_token (will wait until it changes — stale cookies fail exchange).",
            flush=True,
        )

    if not args.no_open:
        print("Opening EmbeddedSetup in your default browser…", flush=True)
        webbrowser.open(EMBEDDED_SETUP)

    print(
        "\nDo this in Chrome:\n"
        "  1. Sign in as %s if asked\n"
        "  2. Click **I agree** on Terms of Service\n"
        "  3. Ignore the forever spinner — that is normal\n"
        "  4. Leave this terminal running; it will pick up the new cookie\n"
        "  5. Approve any macOS Keychain prompt for Chrome cookies\n" % args.email,
        flush=True,
    )

    deadline = time.time() + args.timeout
    oauth = None
    while time.time() < deadline:
        try:
            cur = read_oauth_cookie()
        except Exception as exc:
            print("cookie read error (retrying): %s" % exc, flush=True)
            time.sleep(args.poll)
            continue
        # Need a cookie that differs from baseline (or any cookie if none before).
        if cur and cur != baseline:
            oauth = cur
            print("Fresh oauth_token cookie detected.", flush=True)
            break
        time.sleep(args.poll)
    else:
        print(
            "ERROR: timed out waiting for a new oauth_token cookie.\n"
            "Open DevTools → Application → Cookies → accounts.google.com → "
            "oauth_token, then re-run after a fresh I-agree click.",
            file=sys.stderr,
        )
        return 1

    print("Exchanging oauth → AAS via apkeep…", flush=True)
    try:
        aas = exchange_aas(args.email, oauth)
    except RuntimeError as exc:
        print("ERROR: AAS exchange failed: %s" % exc, file=sys.stderr)
        print(
            "Click I agree again (or restart EmbeddedSetup) for an unused oauth cookie.",
            file=sys.stderr,
        )
        return 1

    write_creds(args.email, aas)
    print(
        "Wrote %s and %s (AAS prefix %s… len %d)" % (PLAY_ENV, APKEEP_INI, aas[:12], len(aas)),
        flush=True,
    )

    # Clear one-time oauth scratch if present
    for scratch in (CONFIG_DIR / "oauth_token.tmp", CONFIG_DIR / "aas_token.tmp"):
        try:
            scratch.unlink()
        except OSError:
            pass

    if args.smoke_test:
        print("Smoke: apkeep --list-versions for a free app…", flush=True)
        r = subprocess.run(
            [
                "apkeep",
                "-a",
                "com.google.android.youtube",
                "-d",
                "google-play",
                "-e",
                args.email,
                "-t",
                aas,
                "--list-versions",
                "/tmp",
            ],
            capture_output=True,
            text=True,
        )
        print("apkeep_rc=%s" % r.returncode, flush=True)
        if r.stdout:
            print(r.stdout[:300], flush=True)
        if r.stderr:
            print(r.stderr[:300], flush=True)

    print(
        "Done. Source before Ansible/play downloads:\n"
        "  source ~/.config/stayturgid/play.env\n"
        "Then mark H1 ready in human/RESPONSES.md (do not paste the token).",
        flush=True,
    )
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except KeyboardInterrupt:
        print("interrupted", file=sys.stderr)
        raise SystemExit(130)
