#!/usr/bin/env python3
"""Project the live OliveTin config from product + user action files (Phase D6).

Design §2 (phase-d-adapter-design-notes) / site-contract §5.3: the live
``~/.config/<site_ns>/olivetin/config.yaml`` has no include mechanism, so it
is a **projection** with a single writer — site-sync. Inputs:

- ``generated/<product>/fragments/olivetin/stayturgid_actions.yaml`` (rendered
  product fragment; action ids must be ``stayturgid_``-prefixed)
- ``<site_dir>/olivetin/user-actions.yaml`` (optional site file, never
  modified; action ids must be ``user_``-prefixed)

Merged output is a pure function of those inputs plus registry port and fixed
site facts (site_ns, home): stable key order, no timestamps, no live probes.
Prefix violations and duplicate ids exit 1. A live config that does not carry
our generated header is foreign — exit 2, never overwritten (single-writer
rule; ``--force-generated`` recovers only files under generated/, not this
one — resolve a foreign live config manually).

The projection refreshes an **existing** live config only. Bootstrap of the
file (first install) stays with the ``serverapp_olivetin`` role, which since
D6 renders it only when absent; site-sync owns every subsequent write.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal

import yaml

PRODUCT = "stayturgid"
GENERATED_MARKER = "GENERATED by stayturgid"
PRODUCT_PREFIX = "stayturgid_"
USER_PREFIX = "user_"
PAGE_TITLE = "Stayturgid Fleet Control"
FRAGMENT_RELATIVE = f"generated/{PRODUCT}/fragments/olivetin/stayturgid_actions.yaml"
USER_ACTIONS_RELATIVE = "olivetin/user-actions.yaml"
_ID_PATTERN = re.compile(r"[a-z][a-z0-9_]*")

ProjectionAction = Literal["overwrite", "skip", "noop"]


@dataclass(frozen=True)
class ProjectionPlan:
    """Planned write (or non-write) of the live OliveTin config."""

    action: ProjectionAction
    live_path: Path | None
    content: bytes | None
    reason: str


def _load_action_list(text: str, *, source: str, required_prefix: str, exc: type[Exception]) -> list[dict[str, Any]]:
    """Parse an actions YAML document and enforce the id prefix contract."""
    try:
        doc = yaml.safe_load(text)
    except yaml.YAMLError as error:
        raise exc(f"cannot parse OliveTin actions from {source}: {error}") from error
    if doc is None:
        return []
    if not isinstance(doc, dict):
        raise exc(f"OliveTin actions document must be a mapping with an 'actions' list: {source}")
    actions_raw = doc.get("actions")
    if actions_raw is None:
        return []
    if not isinstance(actions_raw, list):
        raise exc(f"'actions' must be a list in {source}")
    actions: list[dict[str, Any]] = []
    for index, item in enumerate(actions_raw):
        if not isinstance(item, dict):
            raise exc(f"actions[{index}] must be a mapping in {source}")
        action_id = item.get("id")
        if not isinstance(action_id, str) or not action_id.strip():
            raise exc(f"actions[{index}] is missing a string 'id' in {source}")
        action_id = action_id.strip()
        if not _ID_PATTERN.fullmatch(action_id):
            raise exc(f"action id {action_id!r} must match [a-z][a-z0-9_]* in {source}")
        if not action_id.startswith(required_prefix):
            raise exc(
                f"action id {action_id!r} in {source} must be {required_prefix!r}-prefixed "
                f"(product ids are {PRODUCT_PREFIX!r}-, site user ids {USER_PREFIX!r}-prefixed)"
            )
        actions.append(item)
    return actions


def merge_config(
    *,
    fragment_text: str,
    user_text: str | None,
    listen_address: str,
    webui_dir: str,
    product_version: str,
    product_commit: str,
    exc: type[Exception] = ValueError,
) -> bytes:
    """Deterministically merge product + user actions into the live config bytes."""
    product_actions = _load_action_list(
        fragment_text, source=FRAGMENT_RELATIVE, required_prefix=PRODUCT_PREFIX, exc=exc
    )
    user_actions = (
        _load_action_list(user_text, source=USER_ACTIONS_RELATIVE, required_prefix=USER_PREFIX, exc=exc)
        if user_text is not None
        else []
    )
    seen: set[str] = set()
    for item in [*product_actions, *user_actions]:
        action_id = str(item["id"]).strip()
        if action_id in seen:
            raise exc(f"duplicate OliveTin action id {action_id!r} across product + user actions")
        seen.add(action_id)

    document = {
        "ListenAddressSingleHTTPFrontend": listen_address,
        "WebUIDir": webui_dir,
        "pageTitle": PAGE_TITLE,
        "actions": [*product_actions, *user_actions],
    }
    header = (
        f"# {GENERATED_MARKER} site-sync — DO NOT EDIT (single-writer projection; see design §2)\n"
        "# projection: control/site_contract/olivetin_projection.py "
        f"({FRAGMENT_RELATIVE} + optional {USER_ACTIONS_RELATIVE})\n"
        f"# product_version: {product_version} commit: {product_commit}\n"
    )
    body = yaml.safe_dump(document, default_flow_style=False, sort_keys=False, allow_unicode=True)
    if not body.endswith("\n"):
        body += "\n"
    return (header + body).encode("utf-8")


def _has_generated_header(path: Path) -> bool:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False
    return GENERATED_MARKER in "\n".join(text.splitlines()[:3])


def build_projection(
    *,
    site_dir: Path,
    site_map: Any,
    fragment_content: bytes | None,
    olivetin_port: int | None,
    product_version: str,
    product_commit: str,
    home: Path | None = None,
    exc: type[Exception] = ValueError,
    foreign_exc: type[Exception] | None = None,
) -> ProjectionPlan:
    """Plan the live-config write. Never touches the filesystem beyond reads.

    ``exc`` is raised for exit-1 conditions (bad actions, missing port);
    ``foreign_exc`` (default ``exc``) for the exit-2 foreign-live-config case —
    callers pass typed errors carrying their exit codes.
    """
    foreign = foreign_exc if foreign_exc is not None else exc
    home_path = home if home is not None else Path.home()

    # site_ns is a site fact (inventory/group_vars/all.yml). Sites that never
    # ran D1 (no site_ns) have no site-namespace olivetin — nothing to project.
    # Imported lazily: serverapps imports site_sync which imports this module.
    from control.site_contract.serverapps import ServerAppsError, load_site_ns

    try:
        site_ns = load_site_ns(site_dir, site_map)
    except ServerAppsError:
        return ProjectionPlan(
            action="noop", live_path=None, content=None, reason="site_ns unavailable; olivetin projection skipped"
        )

    live_path = home_path / ".config" / site_ns / "olivetin" / "config.yaml"
    if not live_path.is_file():
        return ProjectionPlan(
            action="noop",
            live_path=live_path,
            content=None,
            reason="live olivetin config absent (bootstrap pending); projection skipped",
        )
    if fragment_content is None:
        return ProjectionPlan(
            action="noop",
            live_path=live_path,
            content=None,
            reason="olivetin fragment not in manifest; projection skipped",
        )
    if olivetin_port is None:
        raise exc(
            "olivetin port missing from the site port registry; register service 'olivetin' "
            "in registry/ports.yml before projecting the live config"
        )
    if not _has_generated_header(live_path):
        raise foreign(
            f"live olivetin config {live_path} does not carry the generated header — "
            "foreign file; refusing to overwrite (single-writer projection). "
            "Move it aside (e.g. to olivetin/user-actions.yaml with user_ ids) and re-run."
        )

    user_path = site_dir / USER_ACTIONS_RELATIVE
    user_text = user_path.read_text(encoding="utf-8") if user_path.is_file() else None

    content = merge_config(
        fragment_text=fragment_content.decode("utf-8"),
        user_text=user_text,
        listen_address=f"127.0.0.1:{olivetin_port}",
        webui_dir=str(home_path / ".local" / "share" / "olivetin" / "webui"),
        product_version=product_version,
        product_commit=product_commit,
        exc=exc,
    )
    if live_path.read_bytes() == content:
        return ProjectionPlan(action="skip", live_path=live_path, content=content, reason="live config up to date")
    return ProjectionPlan(action="overwrite", live_path=live_path, content=content, reason="projected content changed")


def apply_projection(plan: ProjectionPlan) -> None:
    """Write the planned content. The write set is exactly the one live path."""
    if plan.action != "overwrite":
        return
    if plan.live_path is None or plan.content is None:
        raise ValueError("internal error: overwrite projection without path/content")
    plan.live_path.parent.mkdir(parents=True, exist_ok=True)
    plan.live_path.write_bytes(plan.content)
