#!/usr/bin/env python3
"""Site Contract v1 serverapp adapters (Phase D).

Implements ``site-serverapps`` (apply / dry-run) per
``docs/architecture/site-contract.md`` §5 and
``site-djbclark/docs/design/phase-d-adapter-design-notes.md`` §1.

Exit codes (match site-sync):
    0  success / no-op (idempotent re-run returns 0 with all skip)
    1  precondition or execution failure
    2  would touch user-owned content (drifted fragment, missing import line,
       foreign config when site-map forces own)
"""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal, Sequence

from control.site_contract.site_map import SiteMap, SiteMapError, load_site_map
from control.site_contract.site_sync import (
    EXIT_OK,
    EXIT_PRECONDITION,
    EXIT_WOULD_OVERWRITE,
    PRODUCT,
    REPO_ROOT,
    SiteSyncError,
    resolve_site_dir,
)

try:
    import yaml
except ModuleNotFoundError as exc:  # pragma: no cover
    raise SystemExit(
        "error: PyYAML is required for site-serverapps "
        "(install ansible-core, or use the project test venv: just test-venv)"
    ) from exc

Mode = Literal["apply", "dry-run"]
AppMode = Literal["own", "inject", "off"]
ActionKind = Literal["create", "overwrite", "skip", "delete", "verify", "ansible", "noop"]

GENERATED_MARKER = "GENERATED by stayturgid"
KNOWN_APPS = ("caddy",)
DEFAULT_CADDY_DETECT_PATHS = (
    Path.home() / ".config" / "caddy" / "Caddyfile",
    Path("/opt/homebrew/etc/Caddyfile"),
)
OUR_CONFIG_PREFIXES = (Path.home() / ".config" / "stayturgid",)


class ServerAppsError(Exception):
    """Precondition, execution, or user-content refusal for site-serverapps."""

    def __init__(self, message: str, *, exit_code: int = EXIT_PRECONDITION) -> None:
        super().__init__(message)
        self.exit_code = exit_code


@dataclass(frozen=True)
class PlannedAction:
    """One planned serverapp action."""

    app: str
    kind: ActionKind
    target: str
    detail: str = ""


@dataclass
class AppPlan:
    """Resolved mode + planned actions for one serverapp."""

    app: str
    mode: AppMode
    source: str  # site-map | detect | default
    actions: list[PlannedAction] = field(default_factory=list)
    # Inject-mode: rendered fragment path → destination under fragment_dir
    inject_copies: list[tuple[Path, Path]] = field(default_factory=list)
    # Exit-2 messages (missing import, forced-own vs foreign, drift)
    refuse_messages: list[str] = field(default_factory=list)
    # Own-mode ansible extra vars
    ansible_extra: dict[str, str] = field(default_factory=dict)


@dataclass
class ServerAppsPlan:
    """Full multi-app plan (no side effects until apply)."""

    destination: Path
    product_root: Path
    site_ns: str
    apps: list[AppPlan]

    @property
    def refuses(self) -> list[str]:
        out: list[str] = []
        for app in self.apps:
            out.extend(app.refuse_messages)
        return out

    @property
    def has_work(self) -> bool:
        return any(action.kind not in {"skip", "noop", "verify"} for app in self.apps for action in app.actions)


def _sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _first_lines(path: Path, n: int = 3) -> str:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""
    return "\n".join(text.splitlines()[:n])


def _has_generated_header(path: Path) -> bool:
    head = _first_lines(path, 3)
    return GENERATED_MARKER in head or '"_generated"' in head


def _is_under_our_prefixes(path: Path, site_ns: str) -> bool:
    resolved = path.resolve()
    prefixes = list(OUR_CONFIG_PREFIXES) + [Path.home() / ".config" / site_ns]
    for prefix in prefixes:
        try:
            resolved.relative_to(prefix.resolve())
            return True
        except ValueError:
            continue
    return False


def load_site_ns(site_dir: Path, site_map: SiteMap) -> str:
    """Read site_ns from inventory/group_vars/all.yml (site fact)."""
    # Prefer group_vars next to inventory file's parent.
    inventory = site_map.path("inventory")
    candidates = [
        inventory.parent / "group_vars" / "all.yml",
        site_dir / "inventory" / "group_vars" / "all.yml",
    ]
    for path in candidates:
        if not path.is_file():
            continue
        try:
            data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        except (OSError, yaml.YAMLError) as exc:
            raise ServerAppsError(f"cannot parse {path}: {exc}") from exc
        if isinstance(data, dict):
            value = data.get("site_ns")
            if isinstance(value, str) and value.strip():
                ns = value.strip()
                if not re.fullmatch(r"[a-z][a-z0-9_-]*", ns):
                    raise ServerAppsError(f"site_ns must be a lowercase identifier (got {ns!r}) in {path}")
                return ns
    raise ServerAppsError(
        "site_ns missing from inventory/group_vars/all.yml (D1 requires site_ns: <name> — e.g. site_ns: djbclark)"
    )


def _caddy_detect_paths(site_map: SiteMap) -> list[Path]:
    app = site_map.serverapps.get("caddy")
    if app and app.config is not None:
        return [app.config]
    paths = [Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config")) / "caddy" / "Caddyfile"]
    paths.append(Path("/opt/homebrew/etc/Caddyfile"))
    # Dedup preserving order
    seen: set[Path] = set()
    out: list[Path] = []
    for path in paths:
        try:
            resolved = path.expanduser().resolve()
        except OSError:
            resolved = path.expanduser()
        if resolved in seen:
            continue
        seen.add(resolved)
        out.append(resolved)
    return out


def _caddy_fragment_dir(site_map: SiteMap, site_dir: Path) -> Path:
    app = site_map.serverapps.get("caddy")
    if app and app.fragment_dir is not None:
        return app.fragment_dir
    return site_dir / "generated" / PRODUCT / "fragments" / "caddy"


def _generated_caddy_fragments(site_dir: Path) -> list[Path]:
    root = site_dir / "generated" / PRODUCT / "fragments" / "caddy"
    if not root.is_dir():
        return []
    return sorted(p for p in root.glob("*.caddy") if p.is_file())


def resolve_app_mode(
    app: str,
    *,
    site_map: SiteMap,
    site_ns: str,
) -> tuple[AppMode, str]:
    """Deterministic mode selection (§1.2): site-map → foreign detect → own."""
    mapping = site_map.serverapps.get(app)
    if mapping is not None and mapping.mode is not None:
        mode = mapping.mode
        if mode not in {"own", "inject", "off"}:
            raise ServerAppsError(f"serverapps.{app}.mode invalid: {mode!r}")
        return mode, "site-map"  # type: ignore[return-value]

    if app == "caddy":
        for path in _caddy_detect_paths(site_map):
            if not path.is_file():
                continue
            if _is_under_our_prefixes(path, site_ns):
                continue
            if _has_generated_header(path):
                continue
            return "inject", "detect"

    return "own", "default"


def _import_line_covers(caddyfile: Path, fragment_dir: Path) -> bool:
    """True if Caddyfile has an import line covering fragment_dir (glob ok)."""
    if not caddyfile.is_file():
        return False
    try:
        text = caddyfile.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False
    frag = str(fragment_dir.resolve())
    # Accept: import <dir>/*.caddy  OR import <dir>/*  OR import <dir>/file.caddy
    patterns = [
        re.compile(rf"^\s*import\s+{re.escape(frag)}/\*\.caddy\s*$", re.MULTILINE),
        re.compile(rf"^\s*import\s+{re.escape(frag)}/\*\s*$", re.MULTILINE),
        re.compile(rf"^\s*import\s+{re.escape(frag)}/[\w.-]+\.caddy\s*$", re.MULTILINE),
    ]
    # Also accept relative or unexpanded forms containing the path suffix.
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped.startswith("import "):
            continue
        target = stripped[len("import ") :].strip()
        if frag in target and (target.endswith("*.caddy") or target.endswith("/*") or target.endswith(".caddy")):
            return True
        for pat in patterns:
            if pat.search(line):
                return True
    return False


def _suggested_import_line(fragment_dir: Path) -> str:
    return f"import {fragment_dir.resolve()}/*.caddy"


def plan_caddy(
    *,
    site_dir: Path,
    site_map: SiteMap,
    site_ns: str,
    force_generated: bool,
    home: Path | None = None,
) -> AppPlan:
    """Build the plan for the caddy adapter only."""
    mode, source = resolve_app_mode("caddy", site_map=site_map, site_ns=site_ns)
    plan = AppPlan(app="caddy", mode=mode, source=source)
    home_path = home if home is not None else Path.home()
    config_dir = home_path / ".config" / site_ns / "caddy"
    base_config = config_dir / "Caddyfile"
    logs_dir = home_path / ".config" / site_ns / "logs"
    label = f"com.{site_ns}.caddy"
    plist = home_path / "Library" / "LaunchAgents" / f"{label}.plist"
    fragments = _generated_caddy_fragments(site_dir)
    fragment_dir = _caddy_fragment_dir(site_map, site_dir)

    if mode == "off":
        plan.actions.append(
            PlannedAction(app="caddy", kind="noop", target="-", detail="mode=off; fragments stay rendered")
        )
        # List previously placed inject copies (generated-header only) for deletion.
        if (
            fragment_dir.is_dir()
            and fragment_dir.resolve() != (site_dir / "generated" / PRODUCT / "fragments" / "caddy").resolve()
        ):
            for placed in sorted(fragment_dir.glob("*.caddy")):
                if placed.is_file() and _has_generated_header(placed):
                    plan.actions.append(
                        PlannedAction(
                            app="caddy",
                            kind="delete",
                            target=str(placed),
                            detail="off mode removes product-placed inject copies",
                        )
                    )
        return plan

    if mode == "own":
        # Site-map forced own against a foreign config → exit 2.
        if source == "site-map":
            for path in _caddy_detect_paths(site_map):
                if path.is_file() and not _is_under_our_prefixes(path, site_ns) and not _has_generated_header(path):
                    # Only refuse if the foreign path is the site-map config target
                    # and differs from our own destination.
                    app_map = site_map.serverapps.get("caddy")
                    if app_map and app_map.config is not None and path.resolve() == app_map.config.resolve():
                        if path.resolve() != base_config.resolve():
                            plan.refuse_messages.append(
                                f"caddy: site-map forces own but foreign config exists at {path}; "
                                "refusing to overwrite user-owned content (exit 2). "
                                "Set serverapps.caddy.mode: inject, or move the foreign file."
                            )
                            return plan

        if not fragments:
            raise ServerAppsError(
                "caddy own mode requires rendered fragments under "
                f"generated/{PRODUCT}/fragments/caddy/ — run `just site-sync` first"
            )

        plan.ansible_extra = {
            "site_ns": site_ns,
            "site_dir": str(site_dir.resolve()),
            "serverapp_caddy_config_dir": str(config_dir),
            "serverapp_caddy_config_path": str(base_config),
            "serverapp_caddy_logs_dir": str(logs_dir),
            "serverapp_caddy_label": label,
            "serverapp_caddy_plist_path": str(plist),
            "serverapp_caddy_fragment_glob": str(
                (site_dir / "generated" / PRODUCT / "fragments" / "caddy").resolve() / "*.caddy"
            ),
            "serverapp_caddy_home": str(home_path),
            "serverapp_caddy_uid": str(os.getuid()),
        }

        # Plan file-level visibility for dry-run (ansible is the actor for own mode).
        if base_config.is_file():
            plan.actions.append(
                PlannedAction(
                    app="caddy",
                    kind="skip" if _has_generated_header(base_config) else "overwrite",
                    target=str(base_config),
                    detail="own-mode base Caddyfile (via ansible role)",
                )
            )
        else:
            plan.actions.append(
                PlannedAction(
                    app="caddy",
                    kind="create",
                    target=str(base_config),
                    detail="own-mode base Caddyfile (via ansible role)",
                )
            )
        if plist.is_file():
            plan.actions.append(
                PlannedAction(
                    app="caddy",
                    kind="skip",
                    target=str(plist),
                    detail=f"launchd plist {label}",
                )
            )
        else:
            plan.actions.append(
                PlannedAction(
                    app="caddy",
                    kind="create",
                    target=str(plist),
                    detail=f"launchd plist {label}",
                )
            )
        plan.actions.append(
            PlannedAction(
                app="caddy",
                kind="ansible",
                target="serverapp_caddy",
                detail="brew (if absent) + validate + bootstrap + health",
            )
        )
        return plan

    # inject mode
    if not fragments:
        raise ServerAppsError(
            "caddy inject mode requires rendered fragments under "
            f"generated/{PRODUCT}/fragments/caddy/ — run `just site-sync` first"
        )

    # Detect the foreign Caddyfile for import-line verification.
    foreign: Path | None = None
    for path in _caddy_detect_paths(site_map):
        if path.is_file() and not _is_under_our_prefixes(path, site_ns):
            foreign = path
            break
    app_map = site_map.serverapps.get("caddy")
    if app_map and app_map.config is not None:
        foreign = app_map.config

    if foreign is None or not foreign.is_file():
        raise ServerAppsError(
            "caddy inject mode selected but no foreign Caddyfile found at detect paths "
            f"({', '.join(str(p) for p in _caddy_detect_paths(site_map))})"
        )

    if not _import_line_covers(foreign, fragment_dir):
        line = _suggested_import_line(fragment_dir)
        plan.refuse_messages.append(
            f"caddy: inject mode requires an import line in {foreign} covering "
            f"{fragment_dir}. Add exactly:\n  {line}\n"
            "(own mode adds this itself; inject never modifies user base-config content)"
        )
        plan.actions.append(
            PlannedAction(
                app="caddy",
                kind="verify",
                target=str(foreign),
                detail="missing import line → exit 2",
            )
        )
        return plan

    plan.actions.append(
        PlannedAction(
            app="caddy",
            kind="verify",
            target=str(foreign),
            detail="import line present",
        )
    )

    for src in fragments:
        dest = fragment_dir / src.name
        plan.inject_copies.append((src, dest))
        if not dest.exists():
            plan.actions.append(
                PlannedAction(app="caddy", kind="create", target=str(dest), detail="inject fragment copy")
            )
            continue
        if dest.read_bytes() == src.read_bytes():
            plan.actions.append(
                PlannedAction(app="caddy", kind="skip", target=str(dest), detail="inject fragment identical")
            )
            continue
        # Drift: dest differs. If it carries our header, force-generated can recover;
        # if not our header, always exit 2 (user-owned).
        if _has_generated_header(dest):
            if force_generated:
                plan.actions.append(
                    PlannedAction(
                        app="caddy",
                        kind="overwrite",
                        target=str(dest),
                        detail="inject fragment overwrite (--force-generated)",
                    )
                )
            else:
                plan.refuse_messages.append(
                    f"caddy: drifted placed fragment {dest} (hand-edited); "
                    "re-run with --force-generated to overwrite product-placed files only"
                )
                plan.actions.append(
                    PlannedAction(
                        app="caddy",
                        kind="overwrite",
                        target=str(dest),
                        detail="drifted → exit 2 without --force-generated",
                    )
                )
        else:
            plan.refuse_messages.append(f"caddy: refusing to overwrite user-owned file at inject destination {dest}")
            plan.actions.append(
                PlannedAction(
                    app="caddy",
                    kind="overwrite",
                    target=str(dest),
                    detail="user-owned → exit 2",
                )
            )
    return plan


def build_plan(
    *,
    dir_path: str | None = None,
    product_root: Path | None = None,
    env: dict[str, str] | None = None,
    apps: Sequence[str] | None = None,
    force_generated: bool = False,
    home: Path | None = None,
) -> ServerAppsPlan:
    """Compute the full serverapps plan without writing anything."""
    product = (product_root or REPO_ROOT).resolve()
    try:
        destination = resolve_site_dir(dir_path=dir_path, product_root=product, env=env)
    except SiteSyncError as exc:
        raise ServerAppsError(str(exc), exit_code=exc.exit_code) from exc
    try:
        site_map = load_site_map(site_dir=destination, product_root=product)
    except SiteMapError as exc:
        raise ServerAppsError(str(exc)) from exc

    site_ns = load_site_ns(destination, site_map)
    selected = list(apps) if apps else list(KNOWN_APPS)
    unknown = [a for a in selected if a not in KNOWN_APPS]
    if unknown:
        raise ServerAppsError(f"unknown serverapp(s): {', '.join(unknown)}; known: {', '.join(KNOWN_APPS)}")

    app_plans: list[AppPlan] = []
    for app in selected:
        if app == "caddy":
            app_plans.append(
                plan_caddy(
                    site_dir=destination,
                    site_map=site_map,
                    site_ns=site_ns,
                    force_generated=force_generated,
                    home=home,
                )
            )
        else:  # pragma: no cover - guarded by KNOWN_APPS
            raise ServerAppsError(f"no adapter for {app}")

    return ServerAppsPlan(
        destination=destination,
        product_root=product,
        site_ns=site_ns,
        apps=app_plans,
    )


def format_plan(plan: ServerAppsPlan) -> str:
    """Human-readable plan for dry-run / apply logging."""
    lines: list[str] = []
    for app in plan.apps:
        lines.append(f"{app.app}: mode={app.mode} (source={app.source})")
        for action in app.actions:
            detail = f"  {action.detail}" if action.detail else ""
            lines.append(f"  {action.kind:8} {action.target}{detail}")
    return "\n".join(lines) + ("\n" if lines else "")


def _run_ansible_caddy(plan: ServerAppsPlan, app: AppPlan, *, dry_run: bool) -> None:
    """Invoke the serverapp_caddy playbook (own mode)."""
    playbook = plan.product_root / "ansible" / "playbooks" / "serverapps" / "caddy.yml"
    if not playbook.is_file():
        raise ServerAppsError(f"caddy playbook missing: {playbook}")

    if dry_run:
        return

    cmd = [
        "ansible-playbook",
        "-i",
        "localhost,",
        "-c",
        "local",
        str(playbook),
    ]
    for key, value in app.ansible_extra.items():
        cmd.extend(["-e", f"{key}={value}"])

    try:
        result = subprocess.run(
            cmd,
            cwd=str(plan.product_root),
            check=False,
            capture_output=True,
            text=True,
            env={**os.environ, "ANSIBLE_ROLES_PATH": str(plan.product_root / "ansible" / "roles")},
        )
    except OSError as exc:
        raise ServerAppsError(f"failed to run ansible-playbook: {exc}") from exc

    if result.returncode != 0:
        detail = (result.stderr or result.stdout or "").strip()
        raise ServerAppsError(f"ansible serverapp_caddy failed (exit {result.returncode}): {detail[:2000]}")


def apply_plan(
    plan: ServerAppsPlan,
    *,
    force_generated: bool = False,
    dry_run: bool = False,
    skip_ansible: bool = False,
) -> None:
    """Apply planned actions. Refuses on unresolved exit-2 conditions."""
    if plan.refuses and not (force_generated and all("drifted" in m for m in plan.refuses)):
        # force_generated only recovers drifted generated-header files, not missing import.
        recoverable = all("drifted placed fragment" in m or "drifted" in m for m in plan.refuses)
        if not (force_generated and recoverable):
            raise ServerAppsError(
                "\n".join(plan.refuses),
                exit_code=EXIT_WOULD_OVERWRITE,
            )

    for app in plan.apps:
        if app.mode == "off":
            for action in app.actions:
                if action.kind == "delete" and not dry_run:
                    path = Path(action.target)
                    if path.is_file() and _has_generated_header(path):
                        path.unlink()
            continue

        if app.mode == "inject":
            if app.refuse_messages and not force_generated:
                raise ServerAppsError(
                    "\n".join(app.refuse_messages),
                    exit_code=EXIT_WOULD_OVERWRITE,
                )
            for src, dest in app.inject_copies:
                if dry_run:
                    continue
                if dest.exists() and dest.read_bytes() == src.read_bytes():
                    continue
                if dest.exists() and not _has_generated_header(dest) and not force_generated:
                    raise ServerAppsError(
                        f"refusing to overwrite user-owned file: {dest}",
                        exit_code=EXIT_WOULD_OVERWRITE,
                    )
                if (
                    dest.exists()
                    and dest.read_bytes() != src.read_bytes()
                    and _has_generated_header(dest)
                    and not force_generated
                ):
                    raise ServerAppsError(
                        f"drifted placed fragment {dest}; re-run with --force-generated",
                        exit_code=EXIT_WOULD_OVERWRITE,
                    )
                dest.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(src, dest)
            continue

        if app.mode == "own":
            if app.refuse_messages:
                raise ServerAppsError(
                    "\n".join(app.refuse_messages),
                    exit_code=EXIT_WOULD_OVERWRITE,
                )
            if skip_ansible:
                # Test hook: still materialize base config for unit tests without launchd.
                _materialize_caddy_own_for_tests(plan, app, dry_run=dry_run)
                continue
            _run_ansible_caddy(plan, app, dry_run=dry_run)


def _materialize_caddy_own_for_tests(plan: ServerAppsPlan, app: AppPlan, *, dry_run: bool) -> None:
    """Write base Caddyfile + plist without ansible (unit-test / dry scaffolding)."""
    if dry_run:
        return
    config_path = Path(app.ansible_extra["serverapp_caddy_config_path"])
    plist_path = Path(app.ansible_extra["serverapp_caddy_plist_path"])
    logs_dir = Path(app.ansible_extra["serverapp_caddy_logs_dir"])
    label = app.ansible_extra["serverapp_caddy_label"]
    fragment_glob = app.ansible_extra["serverapp_caddy_fragment_glob"]
    home = app.ansible_extra["serverapp_caddy_home"]
    config_path.parent.mkdir(parents=True, exist_ok=True)
    logs_dir.mkdir(parents=True, exist_ok=True)
    health_port = 8080
    body = (
        f"# GENERATED by stayturgid site-sync — DO NOT EDIT (drift → site-sync exit 2)\n"
        f"# template: ansible/roles/serverapp_caddy/templates/Caddyfile.j2\n"
        f"# product_version: test commit: test\n"
        "{\n"
        "\tauto_https disable_redirects\n"
        "\tadmin off\n"
        "}\n"
        "\n"
        f"http://127.0.0.1:{health_port} {{\n"
        '\trespond /health "OK" 200\n'
        "}\n"
        "\n"
        f"import {fragment_glob}\n"
    )
    config_path.write_text(body, encoding="utf-8")
    plist_path.parent.mkdir(parents=True, exist_ok=True)
    caddy_bin = shutil.which("caddy") or "/opt/homebrew/bin/caddy"
    plist = f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{label}</string>
    <key>ProgramArguments</key>
    <array>
        <string>{caddy_bin}</string>
        <string>run</string>
        <string>--config</string>
        <string>{config_path}</string>
        <string>--adapter</string>
        <string>caddyfile</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>{logs_dir}/caddy.log</string>
    <key>StandardErrorPath</key>
    <string>{logs_dir}/caddy.log</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>HOME</key>
        <string>{home}</string>
    </dict>
</dict>
</plist>
"""
    plist_path.write_text(plist, encoding="utf-8")


def _parse_mode(value: str) -> Mode:
    mode = value.strip().lower()
    if mode not in {"apply", "dry-run"}:
        raise ServerAppsError(f"mode must be apply or dry-run; got {value!r}")
    return mode  # type: ignore[return-value]


def _parse_bool_flag(value: str | bool | None) -> bool:
    if value is None or value is False:
        return False
    if value is True:
        return True
    text = str(value).strip().lower()
    if text in {"", "0", "false", "no", "off"}:
        return False
    if text in {"1", "true", "yes", "on"}:
        return True
    raise ServerAppsError(f"force-generated must be 0/1 or true/false; got {value!r}")


def _parse_apps(value: str | None) -> list[str] | None:
    if value is None or not str(value).strip():
        return None
    apps = [part.strip() for part in str(value).split(",") if part.strip()]
    return apps or None


def run_site_serverapps(
    *,
    dir_path: str | None = None,
    mode: str = "apply",
    apps: str | Sequence[str] | None = None,
    force_generated: bool | str = False,
    product_root: Path | None = None,
    env: dict[str, str] | None = None,
    home: Path | None = None,
    skip_ansible: bool = False,
    stdout: object | None = None,
    stderr: object | None = None,
) -> int:
    """Programmatic entry point used by tests and ``main``."""
    out = stdout if stdout is not None else sys.stdout
    err = stderr if stderr is not None else sys.stderr
    try:
        parsed_mode = _parse_mode(mode)
        force = _parse_bool_flag(force_generated)
        if isinstance(apps, str) or apps is None:
            app_list = _parse_apps(apps if isinstance(apps, str) else None)
        else:
            app_list = list(apps)

        plan = build_plan(
            dir_path=dir_path,
            product_root=product_root,
            env=env,
            apps=app_list,
            force_generated=force,
            home=home,
        )
        text = format_plan(plan)
        print(text, end="", file=out)

        if plan.refuses and not (force and all("drifted" in m for m in plan.refuses)):
            recoverable = all("drifted" in m for m in plan.refuses)
            if not (force and recoverable):
                print(f"error: {chr(10).join(plan.refuses)}", file=err)
                return EXIT_WOULD_OVERWRITE

        if parsed_mode == "dry-run":
            return EXIT_OK

        apply_plan(plan, force_generated=force, dry_run=False, skip_ansible=skip_ansible)
        # Summarize
        for app in plan.apps:
            kinds = [a.kind for a in app.actions]
            print(
                f"site-serverapps: {app.app} mode={app.mode} source={app.source} "
                f"actions={','.join(kinds) if kinds else 'none'}",
                file=err,
            )
        return EXIT_OK
    except ServerAppsError as exc:
        print(f"error: {exc}", file=err)
        return exc.exit_code
    except SiteSyncError as exc:
        print(f"error: {exc}", file=err)
        return exc.exit_code
    except OSError as exc:
        print(f"error: {exc}", file=err)
        return EXIT_PRECONDITION


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Activate stayturgid serverapp adapters for a site overlay (Site Contract v1 §5).",
    )
    parser.add_argument("--dir", dest="dir_path", default="", help="explicit site directory")
    parser.add_argument("--mode", default="apply", help="apply (default) or dry-run")
    parser.add_argument("--apps", default="", help="comma-separated app list (default: caddy)")
    parser.add_argument(
        "--force-generated",
        action="store_true",
        default=False,
        help="overwrite drifted product-placed inject fragments only",
    )
    parser.add_argument(
        "assignments",
        nargs="*",
        help="optional KEY=VALUE: dir=, mode=, apps=, force-generated=",
    )
    return parser


def _merge_assignments(
    *,
    dir_path: str,
    mode: str,
    apps: str,
    force_generated: bool,
    assignments: Sequence[str],
) -> tuple[str, str, str, bool]:
    allowed = {"dir", "mode", "apps", "force-generated"}
    values: dict[str, str] = {
        "dir": dir_path,
        "mode": mode,
        "apps": apps,
        "force-generated": "1" if force_generated else "0",
    }
    for token in assignments:
        if "=" not in token:
            raise ServerAppsError(f"unknown argument {token!r}; expected dir= / mode= / apps= / force-generated=")
        key, value = token.split("=", 1)
        if key not in allowed:
            raise ServerAppsError(f"unknown assignment {key!r}; expected one of: {', '.join(sorted(allowed))}")
        values[key] = value
    return values["dir"], values["mode"], values["apps"], _parse_bool_flag(values["force-generated"])


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_arg_parser()
    args = parser.parse_args(list(argv) if argv is not None else None)
    try:
        dir_path, mode, apps, force = _merge_assignments(
            dir_path=args.dir_path,
            mode=args.mode,
            apps=args.apps,
            force_generated=args.force_generated,
            assignments=args.assignments,
        )
    except ServerAppsError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return exc.exit_code
    return run_site_serverapps(
        dir_path=dir_path or None,
        mode=mode,
        apps=apps or None,
        force_generated=force,
    )


if __name__ == "__main__":
    raise SystemExit(main())
