#!/usr/bin/env python3
"""Site Contract v1 serverapp adapters (Phase D).

Implements ``site-serverapps`` (apply / dry-run) per
``docs/architecture/site-contract.md`` §5 and
``site-djbclark/docs/design/phase-d-adapter-design-notes.md`` §1.

Exit codes (match site-sync):
    0  success / no-op (idempotent re-run returns 0 with all skip)
    1  precondition or execution failure
    2  would touch user-owned content (drifted fragment, missing import line,
       foreign config when site-map forces own)
"""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Literal, Sequence

from control.site_contract.site_map import SiteMap, SiteMapError, load_site_map
from control.site_contract.site_sync import (
    EXIT_OK,
    EXIT_PRECONDITION,
    EXIT_WOULD_OVERWRITE,
    PRODUCT,
    REPO_ROOT,
    SiteSyncError,
    load_product_version,
    resolve_site_dir,
)

try:
    import yaml
except ModuleNotFoundError as exc:  # pragma: no cover
    raise SystemExit(
        "error: PyYAML is required for site-serverapps "
        "(install ansible-core, or use the project test venv: just test-venv)"
    ) from exc

Mode = Literal["apply", "dry-run"]
AppMode = Literal["own", "inject", "off"]
ActionKind = Literal["create", "overwrite", "skip", "delete", "verify", "ansible", "noop"]
# Typed refusal kinds (R1 S-2): recoverability is kind-based, not substring.
RefusalKind = Literal["drifted", "user_owned", "missing_include", "forced_own_foreign", "unsupported_mode"]

GENERATED_MARKER = "GENERATED by stayturgid"
KNOWN_APPS = (
    "caddy",
    "vector",
    "openobserve",
    "victoriametrics",
    "grafana",
    "olivetin",
    "landing",
)
OUR_CONFIG_PREFIXES = (Path.home() / ".config" / "stayturgid",)


class ServerAppsError(Exception):
    """Precondition, execution, or user-content refusal for site-serverapps."""

    def __init__(self, message: str, *, exit_code: int = EXIT_PRECONDITION) -> None:
        super().__init__(message)
        self.exit_code = exit_code


@dataclass(frozen=True)
class Refusal:
    """Exit-2 user-content refusal with a typed kind (R1 S-2)."""

    kind: RefusalKind
    message: str


@dataclass(frozen=True)
class PlannedAction:
    """One planned serverapp action."""

    app: str
    kind: ActionKind
    target: str
    detail: str = ""


@dataclass
class AppPlan:
    """Resolved mode + planned actions for one serverapp."""

    app: str
    mode: AppMode
    source: str  # site-map | detect | default
    actions: list[PlannedAction] = field(default_factory=list)
    # Inject-mode: rendered fragment path → destination under fragment_dir
    inject_copies: list[tuple[Path, Path]] = field(default_factory=list)
    # Exit-2 refusals (typed; see RefusalKind)
    refusals: list[Refusal] = field(default_factory=list)
    # Own-mode ansible extra vars
    ansible_extra: dict[str, str] = field(default_factory=dict)

    @property
    def refuse_messages(self) -> list[str]:
        return [r.message for r in self.refusals]


@dataclass
class ServerAppsPlan:
    """Full multi-app plan (no side effects until apply)."""

    destination: Path
    product_root: Path
    site_ns: str
    apps: list[AppPlan]

    @property
    def refuses(self) -> list[str]:
        out: list[str] = []
        for app in self.apps:
            out.extend(app.refuse_messages)
        return out

    @property
    def refusal_list(self) -> list[Refusal]:
        out: list[Refusal] = []
        for app in self.apps:
            out.extend(app.refusals)
        return out

    @property
    def has_work(self) -> bool:
        return any(action.kind not in {"skip", "noop", "verify"} for app in self.apps for action in app.actions)


def _refusals_recoverable_with_force(refusals: Sequence[Refusal]) -> bool:
    """True if every refusal is a drifted product-placed fragment (--force-generated)."""
    return bool(refusals) and all(r.kind == "drifted" for r in refusals)


def _sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _first_lines(path: Path, n: int = 3) -> str:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""
    return "\n".join(text.splitlines()[:n])


def _has_generated_header(path: Path) -> bool:
    head = _first_lines(path, 3)
    return GENERATED_MARKER in head or '"_generated"' in head


def _is_under_our_prefixes(path: Path, site_ns: str, *, home: Path | None = None) -> bool:
    resolved = path.resolve()
    home_path = home if home is not None else Path.home()
    prefixes = list(OUR_CONFIG_PREFIXES) + [home_path / ".config" / site_ns]
    for prefix in prefixes:
        try:
            resolved.relative_to(prefix.resolve())
            return True
        except ValueError:
            continue
    return False


def _load_group_vars_all(site_dir: Path, site_map: SiteMap) -> dict[str, Any]:
    """Load inventory/group_vars/all.yml if present (empty dict otherwise)."""
    inventory = site_map.path("inventory")
    candidates = [
        inventory.parent / "group_vars" / "all.yml",
        site_dir / "inventory" / "group_vars" / "all.yml",
    ]
    for path in candidates:
        if not path.is_file():
            continue
        try:
            data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        except (OSError, yaml.YAMLError) as exc:
            raise ServerAppsError(f"cannot parse {path}: {exc}") from exc
        if isinstance(data, dict):
            return data
    return {}


def load_site_ns(site_dir: Path, site_map: SiteMap) -> str:
    """Read site_ns from inventory/group_vars/all.yml (site fact)."""
    data = _load_group_vars_all(site_dir, site_map)
    value = data.get("site_ns")
    if isinstance(value, str) and value.strip():
        ns = value.strip()
        if not re.fullmatch(r"[a-z][a-z0-9_-]*", ns):
            raise ServerAppsError(f"site_ns must be a lowercase identifier (got {ns!r})")
        return ns
    raise ServerAppsError(
        "site_ns missing from inventory/group_vars/all.yml (D1 requires site_ns: <name> — e.g. site_ns: djbclark)"
    )


def load_caddy_public_hostname(site_dir: Path, site_map: SiteMap) -> str | None:
    """Optional Tailscale MagicDNS name for Choice E front-door subpaths.

    Used for Grafana root_url (/grafana/) and OpenObserve ZO_BASE_URI (/oo).
    """
    data = _load_group_vars_all(site_dir, site_map)
    value = data.get("caddy_public_hostname")
    if isinstance(value, str) and value.strip():
        return value.strip()
    return None


def _caddy_detect_paths(site_map: SiteMap, *, home: Path | None = None) -> list[Path]:
    app = site_map.serverapps.get("caddy")
    if app and app.config is not None:
        return [app.config]
    home_path = home if home is not None else Path.home()
    paths = [Path(os.environ.get("XDG_CONFIG_HOME", home_path / ".config")) / "caddy" / "Caddyfile"]
    paths.append(Path("/opt/homebrew/etc/Caddyfile"))
    # Dedup preserving order
    seen: set[Path] = set()
    out: list[Path] = []
    for path in paths:
        try:
            resolved = path.expanduser().resolve()
        except OSError:
            resolved = path.expanduser()
        if resolved in seen:
            continue
        seen.add(resolved)
        out.append(resolved)
    return out


def _vector_detect_paths(site_map: SiteMap, *, home: Path | None = None) -> list[Path]:
    """§5.3 foreign detect: existing vector.yaml / vector.toml service config.

    Default paths are XDG only. Homebrew ships a sample at
    ``/opt/homebrew/etc/vector/vector.yaml`` on every formula install — treating
    that as foreign would force inject mode for every brew user (DEVIATION from
    a naive reading of §5.3 path list; site-map ``config:`` still covers brew
    or system paths when an operator actually runs from them).
    """
    app = site_map.serverapps.get("vector")
    if app and app.config is not None:
        return [app.config]
    home_path = home if home is not None else Path.home()
    xdg = Path(os.environ.get("XDG_CONFIG_HOME", home_path / ".config"))
    paths = [
        xdg / "vector" / "vector.yaml",
        xdg / "vector" / "vector.toml",
    ]
    seen: set[Path] = set()
    out: list[Path] = []
    for path in paths:
        try:
            resolved = path.expanduser().resolve()
        except OSError:
            resolved = path.expanduser()
        if resolved in seen:
            continue
        seen.add(resolved)
        out.append(resolved)
    return out


def _caddy_fragment_dir(site_map: SiteMap, site_dir: Path) -> Path:
    """Inject-mode copy destination (§5.3).

    DEVIATION (R1 A-3 / M1-Q, recorded in phase-d-adapter-design-notes.md §5):
    without an explicit site-map ``fragment_dir``, this defaults to the
    committed ``generated/`` dir itself — the same place site-sync already
    writes — not an auto-detected foreign include dir. Inject copies degenerate
    to no-ops until an operator sets ``serverapps.caddy.fragment_dir``.
    """
    app = site_map.serverapps.get("caddy")
    if app and app.fragment_dir is not None:
        return app.fragment_dir
    return site_dir / "generated" / PRODUCT / "fragments" / "caddy"


def _vector_fragment_dir(site_map: SiteMap, site_dir: Path) -> Path:
    """Inject-mode copy destination (§5.3); see ``_caddy_fragment_dir`` DEVIATION note."""
    app = site_map.serverapps.get("vector")
    if app and app.fragment_dir is not None:
        return app.fragment_dir
    return site_dir / "generated" / PRODUCT / "fragments" / "vector"


def _generated_caddy_fragments(site_dir: Path) -> list[Path]:
    root = site_dir / "generated" / PRODUCT / "fragments" / "caddy"
    if not root.is_dir():
        return []
    return sorted(p for p in root.glob("*.caddy") if p.is_file())


def _generated_vector_fragments(site_dir: Path) -> list[Path]:
    root = site_dir / "generated" / PRODUCT / "fragments" / "vector"
    if not root.is_dir():
        return []
    return sorted(p for p in root.glob("*.yaml") if p.is_file())


def resolve_app_mode(
    app: str,
    *,
    site_map: SiteMap,
    site_ns: str,
    home: Path | None = None,
) -> tuple[AppMode, str]:
    """Deterministic mode selection (§1.2): site-map → foreign detect → own."""
    mapping = site_map.serverapps.get(app)
    if mapping is not None and mapping.mode is not None:
        mode = mapping.mode
        if mode not in {"own", "inject", "off"}:
            raise ServerAppsError(f"serverapps.{app}.mode invalid: {mode!r}")
        return mode, "site-map"  # type: ignore[return-value]

    if app == "caddy":
        for path in _caddy_detect_paths(site_map, home=home):
            if not path.is_file():
                continue
            if _is_under_our_prefixes(path, site_ns, home=home):
                continue
            if _has_generated_header(path):
                continue
            return "inject", "detect"

    if app == "vector":
        for path in _vector_detect_paths(site_map, home=home):
            if not path.is_file():
                continue
            if _is_under_our_prefixes(path, site_ns, home=home):
                continue
            if _has_generated_header(path):
                continue
            return "inject", "detect"

    if app == "openobserve":
        # §5.3: single-owner; inject if a foreign unit/config is present.
        # Legacy com.stayturgid.* and com.<site_ns>.* are not foreign.
        for path in _openobserve_detect_paths(site_map, site_ns=site_ns, home=home):
            if path.is_file():
                return "inject", "detect"

    if app == "victoriametrics":
        # §5.3: single-owner; inject = reuse registry endpoint only.
        for path in _victoriametrics_detect_paths(site_map, site_ns=site_ns, home=home):
            if path.is_file():
                return "inject", "detect"

    if app == "grafana":
        for path in _grafana_detect_paths(site_map, site_ns=site_ns, home=home):
            if path.is_file():
                return "inject", "detect"

    if app == "olivetin":
        for path in _olivetin_detect_paths(site_map, site_ns=site_ns, home=home):
            if path.is_file():
                return "inject", "detect"

    return "own", "default"


def _import_line_covers(caddyfile: Path, fragment_dir: Path) -> bool:
    """True if Caddyfile has an import line covering fragment_dir (glob ok).

    Every accepted form is anchored so ``fragment_dir`` must be followed by a
    literal ``/`` (or be the exact final path segment) — a naive substring
    check would also accept a sibling directory whose name happens to start
    with the same characters (e.g. fragment_dir ``/etc/caddy.d`` wrongly
    "covered" by an import of ``/etc/caddy.d-other/*.caddy``).
    """
    if not caddyfile.is_file():
        return False
    try:
        text = caddyfile.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False
    frag = str(fragment_dir.resolve())
    # Accept: import <dir>/*.caddy  OR import <dir>/*  OR import <dir>/file.caddy
    patterns = [
        re.compile(rf"^\s*import\s+{re.escape(frag)}/\*\.caddy\s*$", re.MULTILINE),
        re.compile(rf"^\s*import\s+{re.escape(frag)}/\*\s*$", re.MULTILINE),
        re.compile(rf"^\s*import\s+{re.escape(frag)}/[\w.-]+\.caddy\s*$", re.MULTILINE),
    ]
    return any(pattern.search(text) for pattern in patterns)


def _suggested_import_line(fragment_dir: Path) -> str:
    return f"import {fragment_dir.resolve()}/*.caddy"


def _vector_unit_includes_fragments(fragment_dir: Path, home: Path) -> bool:
    """True if a known launchd plist already passes --config for fragment_dir.

    A launchd ``ProgramArguments`` array renders each argument as its own
    ``<string>`` element, so ``--config`` and its value are never on the same
    line/adjacent text — this matches consecutive ``<string>--config</string>``
    / ``<string><value></string>`` pairs and checks the *value* is fragment_dir
    itself or a path under it. The previous implementation just checked
    whether the fragment_dir string appeared anywhere in the plist at all
    (no association with ``--config``, no path-boundary check), which both
    false-positived on any incidental text match and false-positived on a
    sibling directory with a name-prefix collision (e.g. fragment_dir
    ``/etc/vector.d`` "covered" by an unrelated ``--config
    /etc/vector.d-other/foo.yaml``).
    """
    frag = fragment_dir.resolve()
    pair_pattern = re.compile(r"<string>\s*--config\s*</string>\s*<string>\s*([^<]+?)\s*</string>")

    def _covers(text: str) -> bool:
        for match in pair_pattern.finditer(text):
            try:
                value = Path(match.group(1)).resolve()
            except OSError:
                continue
            if value == frag or value.is_relative_to(frag):
                return True
        return False

    candidates = [
        home / "Library" / "LaunchAgents" / "com.stayturgid.vector.plist",
        Path("/Library/LaunchAgents/com.stayturgid.vector.plist"),
        Path("/Library/LaunchDaemons/vector.plist"),
    ]
    # Also any com.*.vector.plist under user LaunchAgents (site or other).
    agents = home / "Library" / "LaunchAgents"
    if agents.is_dir():
        candidates.extend(sorted(agents.glob("*.vector.plist")))
    seen: set[Path] = set()
    for path in candidates:
        try:
            resolved = path.resolve()
        except OSError:
            continue
        if resolved in seen or not path.is_file():
            continue
        seen.add(resolved)
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        if _covers(text):
            return True
    return False


def _suggested_vector_config_args(fragments: Sequence[Path]) -> str:
    lines = [f"  --config {p.resolve()}" for p in fragments]
    return "\n".join(lines) if lines else "  --config <fragment.yaml>"


def _openobserve_detect_paths(
    site_map: SiteMap,
    *,
    site_ns: str,
    home: Path | None = None,
) -> list[Path]:
    """§5.3 foreign detect: existing openobserve unit/config outside our labels.

    Returns paths that, if present as files, indicate a foreign-managed
    OpenObserve (inject = reuse registry endpoint only). Product legacy
    ``com.stayturgid.openobserve`` and site ``com.<site_ns>.openobserve``
    are excluded so re-runs stay own-mode for the Phase D migration.
    """
    app = site_map.serverapps.get("openobserve")
    if app and app.config is not None:
        return [app.config]
    # Only well-known foreign unit paths — do NOT glob com.*.openobserve under
    # LaunchAgents (another site's com.<ns>.openobserve would force inject).
    del site_ns  # reserved for future site-map-relative detection
    home_path = home if home is not None else Path.home()
    candidates = [
        home_path / "Library" / "LaunchAgents" / "io.openobserve.openobserve.plist",
        Path("/Library/LaunchDaemons/openobserve.plist"),
        Path("/Library/LaunchAgents/openobserve.plist"),
        Path("/opt/homebrew/opt/openobserve/homebrew.mxcl.openobserve.plist"),
    ]
    seen: set[Path] = set()
    out: list[Path] = []
    for path in candidates:
        try:
            resolved = path.expanduser().resolve()
        except OSError:
            resolved = path.expanduser()
        if resolved in seen:
            continue
        seen.add(resolved)
        out.append(resolved)
    return out


def plan_caddy(
    *,
    site_dir: Path,
    site_map: SiteMap,
    site_ns: str,
    force_generated: bool,
    home: Path | None = None,
    product_version: str | None = None,
) -> AppPlan:
    """Build the plan for the caddy adapter only."""
    mode, source = resolve_app_mode("caddy", site_map=site_map, site_ns=site_ns, home=home)
    plan = AppPlan(app="caddy", mode=mode, source=source)
    home_path = home if home is not None else Path.home()
    config_dir = home_path / ".config" / site_ns / "caddy"
    base_config = config_dir / "Caddyfile"
    logs_dir = home_path / ".config" / site_ns / "logs"
    label = f"com.{site_ns}.caddy"
    plist = home_path / "Library" / "LaunchAgents" / f"{label}.plist"
    fragments = _generated_caddy_fragments(site_dir)
    fragment_dir = _caddy_fragment_dir(site_map, site_dir)

    if mode == "off":
        plan.actions.append(
            PlannedAction(app="caddy", kind="noop", target="-", detail="mode=off; fragments stay rendered")
        )
        # List previously placed inject copies (generated-header only) for deletion.
        if (
            fragment_dir.is_dir()
            and fragment_dir.resolve() != (site_dir / "generated" / PRODUCT / "fragments" / "caddy").resolve()
        ):
            for placed in sorted(fragment_dir.glob("*.caddy")):
                if placed.is_file() and _has_generated_header(placed):
                    plan.actions.append(
                        PlannedAction(
                            app="caddy",
                            kind="delete",
                            target=str(placed),
                            detail="off mode removes product-placed inject copies",
                        )
                    )
        return plan

    if mode == "own":
        # Site-map forced own against a foreign config → exit 2.
        if source == "site-map":
            for path in _caddy_detect_paths(site_map, home=home_path):
                if (
                    path.is_file()
                    and not _is_under_our_prefixes(path, site_ns, home=home_path)
                    and not _has_generated_header(path)
                ):
                    # Only refuse if the foreign path is the site-map config target
                    # and differs from our own destination.
                    app_map = site_map.serverapps.get("caddy")
                    if app_map and app_map.config is not None and path.resolve() == app_map.config.resolve():
                        if path.resolve() != base_config.resolve():
                            plan.refusals.append(
                                Refusal(
                                    kind="forced_own_foreign",
                                    message=(
                                        f"caddy: site-map forces own but foreign config exists at {path}; "
                                        "refusing to overwrite user-owned content (exit 2). "
                                        "Set serverapps.caddy.mode: inject, or move the foreign file."
                                    ),
                                )
                            )
                            return plan

        if not fragments:
            raise ServerAppsError(
                "caddy own mode requires rendered fragments under "
                f"generated/{PRODUCT}/fragments/caddy/ — run `just site-sync` first"
            )

        plan.ansible_extra = {
            "site_ns": site_ns,
            "site_dir": str(site_dir.resolve()),
            "serverapp_caddy_config_dir": str(config_dir),
            "serverapp_caddy_config_path": str(base_config),
            "serverapp_caddy_logs_dir": str(logs_dir),
            "serverapp_caddy_label": label,
            "serverapp_caddy_plist_path": str(plist),
            "serverapp_caddy_fragment_glob": str(
                (site_dir / "generated" / PRODUCT / "fragments" / "caddy").resolve() / "*.caddy"
            ),
            "serverapp_caddy_home": str(home_path),
            "serverapp_caddy_uid": str(os.getuid()),
            "product_version": product_version or "unknown",
        }

        # Plan file-level visibility for dry-run (ansible is the actor for own mode).
        if base_config.is_file():
            plan.actions.append(
                PlannedAction(
                    app="caddy",
                    kind="skip" if _has_generated_header(base_config) else "overwrite",
                    target=str(base_config),
                    detail="own-mode base Caddyfile (via ansible role)",
                )
            )
        else:
            plan.actions.append(
                PlannedAction(
                    app="caddy",
                    kind="create",
                    target=str(base_config),
                    detail="own-mode base Caddyfile (via ansible role)",
                )
            )
        if plist.is_file():
            plan.actions.append(
                PlannedAction(
                    app="caddy",
                    kind="skip",
                    target=str(plist),
                    detail=f"launchd plist {label}",
                )
            )
        else:
            plan.actions.append(
                PlannedAction(
                    app="caddy",
                    kind="create",
                    target=str(plist),
                    detail=f"launchd plist {label}",
                )
            )
        plan.actions.append(
            PlannedAction(
                app="caddy",
                kind="ansible",
                target="serverapp_caddy",
                detail="brew (if absent) + validate + bootstrap + health",
            )
        )
        return plan

    # inject mode
    if not fragments:
        raise ServerAppsError(
            "caddy inject mode requires rendered fragments under "
            f"generated/{PRODUCT}/fragments/caddy/ — run `just site-sync` first"
        )

    # Detect the foreign Caddyfile for import-line verification.
    foreign: Path | None = None
    for path in _caddy_detect_paths(site_map, home=home_path):
        if path.is_file() and not _is_under_our_prefixes(path, site_ns, home=home_path):
            foreign = path
            break
    app_map = site_map.serverapps.get("caddy")
    if app_map and app_map.config is not None:
        foreign = app_map.config

    if foreign is None or not foreign.is_file():
        raise ServerAppsError(
            "caddy inject mode selected but no foreign Caddyfile found at detect paths "
            f"({', '.join(str(p) for p in _caddy_detect_paths(site_map, home=home_path))})"
        )

    if not _import_line_covers(foreign, fragment_dir):
        line = _suggested_import_line(fragment_dir)
        plan.refusals.append(
            Refusal(
                kind="missing_include",
                message=(
                    f"caddy: inject mode requires an import line in {foreign} covering "
                    f"{fragment_dir}. Add exactly:\n  {line}\n"
                    "(own mode adds this itself; inject never modifies user base-config content)"
                ),
            )
        )
        plan.actions.append(
            PlannedAction(
                app="caddy",
                kind="verify",
                target=str(foreign),
                detail="missing import line → exit 2",
            )
        )
        return plan

    plan.actions.append(
        PlannedAction(
            app="caddy",
            kind="verify",
            target=str(foreign),
            detail="import line present",
        )
    )

    for src in fragments:
        dest = fragment_dir / src.name
        plan.inject_copies.append((src, dest))
        if not dest.exists():
            plan.actions.append(
                PlannedAction(app="caddy", kind="create", target=str(dest), detail="inject fragment copy")
            )
            continue
        if dest.read_bytes() == src.read_bytes():
            plan.actions.append(
                PlannedAction(app="caddy", kind="skip", target=str(dest), detail="inject fragment identical")
            )
            continue
        # Drift: dest differs. If it carries our header, force-generated can recover;
        # if not our header, always exit 2 (user-owned).
        if _has_generated_header(dest):
            if force_generated:
                plan.actions.append(
                    PlannedAction(
                        app="caddy",
                        kind="overwrite",
                        target=str(dest),
                        detail="inject fragment overwrite (--force-generated)",
                    )
                )
            else:
                plan.refusals.append(
                    Refusal(
                        kind="drifted",
                        message=(
                            f"caddy: drifted placed fragment {dest} (hand-edited); "
                            "re-run with --force-generated to overwrite product-placed files only"
                        ),
                    )
                )
                plan.actions.append(
                    PlannedAction(
                        app="caddy",
                        kind="overwrite",
                        target=str(dest),
                        detail="drifted → exit 2 without --force-generated",
                    )
                )
        else:
            plan.refusals.append(
                Refusal(
                    kind="user_owned",
                    message=f"caddy: refusing to overwrite user-owned file at inject destination {dest}",
                )
            )
            plan.actions.append(
                PlannedAction(
                    app="caddy",
                    kind="overwrite",
                    target=str(dest),
                    detail="user-owned → exit 2",
                )
            )
    return plan


def plan_vector(
    *,
    site_dir: Path,
    site_map: SiteMap,
    site_ns: str,
    force_generated: bool,
    home: Path | None = None,
    product_version: str | None = None,
) -> AppPlan:
    """Build the plan for the vector adapter (clone of plan_caddy; multi --config)."""
    mode, source = resolve_app_mode("vector", site_map=site_map, site_ns=site_ns, home=home)
    plan = AppPlan(app="vector", mode=mode, source=source)
    home_path = home if home is not None else Path.home()
    config_dir = home_path / ".config" / site_ns / "vector"
    base_config = config_dir / "vector.yaml"
    data_dir = config_dir / "data"
    logs_dir = home_path / ".config" / site_ns / "logs"
    label = f"com.{site_ns}.vector"
    plist = home_path / "Library" / "LaunchAgents" / f"{label}.plist"
    fragments = _generated_vector_fragments(site_dir)
    fragment_dir = _vector_fragment_dir(site_map, site_dir)
    generated_root = site_dir / "generated" / PRODUCT / "fragments" / "vector"

    if mode == "off":
        plan.actions.append(
            PlannedAction(app="vector", kind="noop", target="-", detail="mode=off; fragments stay rendered")
        )
        if fragment_dir.is_dir() and fragment_dir.resolve() != generated_root.resolve():
            for placed in sorted(fragment_dir.glob("*.yaml")):
                if placed.is_file() and _has_generated_header(placed):
                    plan.actions.append(
                        PlannedAction(
                            app="vector",
                            kind="delete",
                            target=str(placed),
                            detail="off mode removes product-placed inject copies",
                        )
                    )
        return plan

    if mode == "own":
        if source == "site-map":
            for path in _vector_detect_paths(site_map, home=home_path):
                if (
                    path.is_file()
                    and not _is_under_our_prefixes(path, site_ns, home=home_path)
                    and not _has_generated_header(path)
                ):
                    app_map = site_map.serverapps.get("vector")
                    if app_map and app_map.config is not None and path.resolve() == app_map.config.resolve():
                        if path.resolve() != base_config.resolve():
                            plan.refusals.append(
                                Refusal(
                                    kind="forced_own_foreign",
                                    message=(
                                        f"vector: site-map forces own but foreign config exists at {path}; "
                                        "refusing to overwrite user-owned content (exit 2). "
                                        "Set serverapps.vector.mode: inject, or move the foreign file."
                                    ),
                                )
                            )
                            return plan

        if not fragments:
            raise ServerAppsError(
                "vector own mode requires rendered fragments under "
                f"generated/{PRODUCT}/fragments/vector/ — run `just site-sync` first"
            )

        # Comma-separated absolute paths for ansible plist --config args (no shell glob).
        fragment_csv = ",".join(str(p.resolve()) for p in fragments)
        plan.ansible_extra = {
            "site_ns": site_ns,
            "site_dir": str(site_dir.resolve()),
            "serverapp_vector_config_dir": str(config_dir),
            "serverapp_vector_config_path": str(base_config),
            "serverapp_vector_data_dir": str(data_dir),
            "serverapp_vector_logs_dir": str(logs_dir),
            "serverapp_vector_label": label,
            "serverapp_vector_plist_path": str(plist),
            "serverapp_vector_fragment_configs": fragment_csv,
            "serverapp_vector_home": str(home_path),
            "serverapp_vector_uid": str(os.getuid()),
            "product_version": product_version or "unknown",
        }

        if base_config.is_file():
            plan.actions.append(
                PlannedAction(
                    app="vector",
                    kind="skip" if _has_generated_header(base_config) else "overwrite",
                    target=str(base_config),
                    detail="own-mode base vector.yaml (via ansible role)",
                )
            )
        else:
            plan.actions.append(
                PlannedAction(
                    app="vector",
                    kind="create",
                    target=str(base_config),
                    detail="own-mode base vector.yaml (via ansible role)",
                )
            )
        if plist.is_file():
            plan.actions.append(
                PlannedAction(
                    app="vector",
                    kind="skip",
                    target=str(plist),
                    detail=f"launchd plist {label}",
                )
            )
        else:
            plan.actions.append(
                PlannedAction(
                    app="vector",
                    kind="create",
                    target=str(plist),
                    detail=f"launchd plist {label}",
                )
            )
        plan.actions.append(
            PlannedAction(
                app="vector",
                kind="ansible",
                target="serverapp_vector",
                detail="brew (if absent) + validate + bootstrap + health",
            )
        )
        return plan

    # inject mode
    if not fragments:
        raise ServerAppsError(
            "vector inject mode requires rendered fragments under "
            f"generated/{PRODUCT}/fragments/vector/ — run `just site-sync` first"
        )

    foreign: Path | None = None
    for path in _vector_detect_paths(site_map, home=home_path):
        if path.is_file() and not _is_under_our_prefixes(path, site_ns, home=home_path):
            foreign = path
            break
    app_map = site_map.serverapps.get("vector")
    if app_map and app_map.config is not None:
        foreign = app_map.config

    if foreign is None or not foreign.is_file():
        raise ServerAppsError(
            "vector inject mode selected but no foreign vector config found at detect paths "
            f"({', '.join(str(p) for p in _vector_detect_paths(site_map, home=home_path))})"
        )

    # Include mechanism: unit must pass --config for each product fragment (§5.3).
    if not _vector_unit_includes_fragments(fragment_dir, home_path):
        args = _suggested_vector_config_args(fragments)
        plan.refusals.append(
            Refusal(
                kind="missing_include",
                message=(
                    f"vector: inject mode requires the vector unit to pass extra --config args "
                    f"for product fragments under {fragment_dir}. Add exactly:\n{args}\n"
                    "(own mode wires this in the site-namespace plist; inject never modifies the unit)"
                ),
            )
        )
        plan.actions.append(
            PlannedAction(
                app="vector",
                kind="verify",
                target=str(foreign),
                detail="missing --config fragment args → exit 2",
            )
        )
        return plan

    plan.actions.append(
        PlannedAction(
            app="vector",
            kind="verify",
            target=str(foreign),
            detail="unit --config args cover fragment_dir",
        )
    )

    for src in fragments:
        dest = fragment_dir / src.name
        plan.inject_copies.append((src, dest))
        if not dest.exists():
            plan.actions.append(
                PlannedAction(app="vector", kind="create", target=str(dest), detail="inject fragment copy")
            )
            continue
        if dest.read_bytes() == src.read_bytes():
            plan.actions.append(
                PlannedAction(app="vector", kind="skip", target=str(dest), detail="inject fragment identical")
            )
            continue
        if _has_generated_header(dest):
            if force_generated:
                plan.actions.append(
                    PlannedAction(
                        app="vector",
                        kind="overwrite",
                        target=str(dest),
                        detail="inject fragment overwrite (--force-generated)",
                    )
                )
            else:
                plan.refusals.append(
                    Refusal(
                        kind="drifted",
                        message=(
                            f"vector: drifted placed fragment {dest} (hand-edited); "
                            "re-run with --force-generated to overwrite product-placed files only"
                        ),
                    )
                )
                plan.actions.append(
                    PlannedAction(
                        app="vector",
                        kind="overwrite",
                        target=str(dest),
                        detail="drifted → exit 2 without --force-generated",
                    )
                )
        else:
            plan.refusals.append(
                Refusal(
                    kind="user_owned",
                    message=f"vector: refusing to overwrite user-owned file at inject destination {dest}",
                )
            )
            plan.actions.append(
                PlannedAction(
                    app="vector",
                    kind="overwrite",
                    target=str(dest),
                    detail="user-owned → exit 2",
                )
            )
    return plan


def plan_openobserve(
    *,
    site_dir: Path,
    site_map: SiteMap,
    site_ns: str,
    force_generated: bool,
    home: Path | None = None,
) -> AppPlan:
    """Build the plan for the openobserve adapter (single-owner; §5.3).

    Inject mode: zero file writes — only verify/reuse the registry endpoint.
    Own mode: ansible role installs binary if absent, site-namespace unit,
    keeps data dir at ~/.local/share/openobserve/data.
    """
    del force_generated  # no inject fragment copies for openobserve
    mode, source = resolve_app_mode("openobserve", site_map=site_map, site_ns=site_ns, home=home)
    plan = AppPlan(app="openobserve", mode=mode, source=source)
    home_path = home if home is not None else Path.home()
    # Data dir is intentionally NOT under site_ns — must match live path.
    data_dir = home_path / ".local" / "share" / "openobserve" / "data"
    bin_path = home_path / ".local" / "bin" / "openobserve"
    logs_dir = home_path / ".config" / site_ns / "logs"
    label = f"com.{site_ns}.openobserve"
    plist = home_path / "Library" / "LaunchAgents" / f"{label}.plist"
    # Inject/off keep loopback root health (no ZO_BASE_URI). Own mode may remap.
    health_url = "http://127.0.0.1:5080/healthz"

    if mode == "off":
        plan.actions.append(
            PlannedAction(
                app="openobserve",
                kind="noop",
                target="-",
                detail="mode=off; no activation (single-owner; no inject copies)",
            )
        )
        return plan

    if mode == "inject":
        # Zero file writes — product reuses the registry endpoint only (§5.3).
        plan.actions.append(
            PlannedAction(
                app="openobserve",
                kind="verify",
                target=health_url,
                detail="inject: reuse openobserve-http endpoint from registry (no file writes)",
            )
        )
        plan.actions.append(
            PlannedAction(
                app="openobserve",
                kind="noop",
                target="registry:openobserve-http",
                detail="inject mode never installs, never writes unit/config",
            )
        )
        return plan

    # own mode
    if source == "site-map":
        for path in _openobserve_detect_paths(site_map, site_ns=site_ns, home=home_path):
            if not path.is_file():
                continue
            app_map = site_map.serverapps.get("openobserve")
            if app_map and app_map.config is not None and path.resolve() == app_map.config.resolve():
                if path.resolve() != plist.resolve():
                    plan.refusals.append(
                        Refusal(
                            kind="forced_own_foreign",
                            message=(
                                f"openobserve: site-map forces own but foreign unit/config exists at {path}; "
                                "refusing to take over user-owned OpenObserve (exit 2). "
                                "Set serverapps.openobserve.mode: inject, or remove the foreign unit."
                            ),
                        )
                    )
                    return plan

    public_host = load_caddy_public_hostname(site_dir, site_map)
    # Choice E (D7-ROUTES-E): ZO_BASE_URI remaps *all* HTTP routes (UI + API +
    # healthz) under the prefix. Vector sink + health_url must match.
    if public_host:
        oo_base_uri = "/oo"
        oo_web_url = f"https://{public_host}/oo"
        health_url = f"http://127.0.0.1:5080{oo_base_uri}/healthz"
    else:
        oo_base_uri = ""
        oo_web_url = ""

    plan.ansible_extra = {
        "site_ns": site_ns,
        "site_dir": str(site_dir.resolve()),
        "serverapp_openobserve_home": str(home_path),
        "serverapp_openobserve_data_dir": str(data_dir),
        "serverapp_openobserve_bin_path": str(bin_path),
        "serverapp_openobserve_logs_dir": str(logs_dir),
        "serverapp_openobserve_label": label,
        "serverapp_openobserve_plist_path": str(plist),
        "serverapp_openobserve_health_url": health_url,
        "serverapp_openobserve_uid": str(os.getuid()),
        "serverapp_openobserve_base_uri": oo_base_uri,
        "serverapp_openobserve_web_url": oo_web_url,
    }

    if plist.is_file():
        plan.actions.append(
            PlannedAction(
                app="openobserve",
                kind="skip",
                target=str(plist),
                detail=f"launchd plist {label}",
            )
        )
    else:
        plan.actions.append(
            PlannedAction(
                app="openobserve",
                kind="create",
                target=str(plist),
                detail=f"launchd plist {label}",
            )
        )
    plan.actions.append(
        PlannedAction(
            app="openobserve",
            kind="verify",
            target=str(data_dir),
            detail="data dir path retained (~/.local/share/openobserve/data)",
        )
    )
    plan.actions.append(
        PlannedAction(
            app="openobserve",
            kind="ansible",
            target="serverapp_openobserve",
            detail="binary (if absent) + bootstrap + health (data dir unchanged)",
        )
    )
    return plan


def _victoriametrics_detect_paths(
    site_map: SiteMap,
    *,
    site_ns: str,
    home: Path | None = None,
) -> list[Path]:
    """§5.3 foreign detect for VictoriaMetrics (well-known foreign units only).

    DEVIATION: exclude brew formula service definitions under
    ``/opt/homebrew/opt/…`` (always present after ``brew install``; would
    force inject on every own-mode re-run). Site-map ``config:`` still covers
    real foreign paths.
    """
    app = site_map.serverapps.get("victoriametrics")
    if app and app.config is not None:
        return [app.config]
    del site_ns
    home_path = home if home is not None else Path.home()
    candidates = [
        home_path / "Library" / "LaunchAgents" / "homebrew.mxcl.victoriametrics.plist",
        Path("/Library/LaunchDaemons/victoriametrics.plist"),
        Path("/Library/LaunchDaemons/homebrew.mxcl.victoriametrics.plist"),
    ]
    seen: set[Path] = set()
    out: list[Path] = []
    for path in candidates:
        try:
            resolved = path.expanduser().resolve()
        except OSError:
            resolved = path.expanduser()
        if resolved in seen:
            continue
        seen.add(resolved)
        out.append(resolved)
    return out


def _grafana_detect_paths(
    site_map: SiteMap,
    *,
    site_ns: str,
    home: Path | None = None,
) -> list[Path]:
    """§5.3 foreign detect for Grafana.

    DEVIATION: do not treat brew sample ``/opt/homebrew/etc/grafana/grafana.ini``
    or formula service definitions as foreign (same class as vector XDG-only /
    openobserve well-known-only). Detect only user-domain brew-services plists
    and system LaunchDaemons. Site-map ``config:`` still covers real foreign
    ini paths when an operator runs from them.
    """
    app = site_map.serverapps.get("grafana")
    if app and app.config is not None:
        return [app.config]
    del site_ns
    home_path = home if home is not None else Path.home()
    candidates = [
        home_path / "Library" / "LaunchAgents" / "homebrew.mxcl.grafana.plist",
        Path("/Library/LaunchDaemons/homebrew.mxcl.grafana.plist"),
        Path("/Library/LaunchDaemons/grafana.plist"),
    ]
    seen: set[Path] = set()
    out: list[Path] = []
    for path in candidates:
        try:
            resolved = path.expanduser().resolve()
        except OSError:
            resolved = path.expanduser()
        if resolved in seen:
            continue
        seen.add(resolved)
        out.append(resolved)
    return out


def _olivetin_detect_paths(
    site_map: SiteMap,
    *,
    site_ns: str,
    home: Path | None = None,
) -> list[Path]:
    """§5.3 foreign detect: existing config.yaml outside our prefixes."""
    app = site_map.serverapps.get("olivetin")
    if app and app.config is not None:
        return [app.config]
    del site_ns
    home_path = home if home is not None else Path.home()
    xdg = Path(os.environ.get("XDG_CONFIG_HOME", home_path / ".config"))
    candidates = [
        xdg / "OliveTin" / "config.yaml",
        Path("/etc/OliveTin/config.yaml"),
        home_path / "Library" / "LaunchAgents" / "com.olivetin.olivetin.plist",
    ]
    seen: set[Path] = set()
    out: list[Path] = []
    for path in candidates:
        try:
            resolved = path.expanduser().resolve()
        except OSError:
            resolved = path.expanduser()
        if resolved in seen:
            continue
        seen.add(resolved)
        out.append(resolved)
    return out


def plan_victoriametrics(
    *,
    site_dir: Path,
    site_map: SiteMap,
    site_ns: str,
    force_generated: bool,
    home: Path | None = None,
    product_version: str | None = None,
) -> AppPlan:
    """Build the plan for the victoriametrics adapter (single-owner; §5.3).

    Inject mode: zero file writes — reuse registry endpoint only.
    Own mode: ansible role brew-if-absent + site-namespace unit on 8428.
    """
    del force_generated
    mode, source = resolve_app_mode("victoriametrics", site_map=site_map, site_ns=site_ns, home=home)
    plan = AppPlan(app="victoriametrics", mode=mode, source=source)
    home_path = home if home is not None else Path.home()
    config_dir = home_path / ".config" / site_ns / "victoriametrics"
    scrape_path = config_dir / "scrape.yml"
    data_dir = config_dir / "data"
    logs_dir = home_path / ".config" / site_ns / "logs"
    label = f"com.{site_ns}.victoriametrics"
    plist = home_path / "Library" / "LaunchAgents" / f"{label}.plist"
    health_url = "http://127.0.0.1:8428/health"

    if mode == "off":
        plan.actions.append(
            PlannedAction(
                app="victoriametrics",
                kind="noop",
                target="-",
                detail="mode=off; no activation (single-owner; no inject copies)",
            )
        )
        return plan

    if mode == "inject":
        plan.actions.append(
            PlannedAction(
                app="victoriametrics",
                kind="verify",
                target=health_url,
                detail="inject: reuse victoriametrics endpoint from registry (no file writes)",
            )
        )
        plan.actions.append(
            PlannedAction(
                app="victoriametrics",
                kind="noop",
                target="registry:victoriametrics",
                detail="inject mode never installs, never writes unit/config",
            )
        )
        return plan

    if source == "site-map":
        for path in _victoriametrics_detect_paths(site_map, site_ns=site_ns, home=home_path):
            if not path.is_file():
                continue
            app_map = site_map.serverapps.get("victoriametrics")
            if app_map and app_map.config is not None and path.resolve() == app_map.config.resolve():
                if path.resolve() != plist.resolve():
                    plan.refusals.append(
                        Refusal(
                            kind="forced_own_foreign",
                            message=(
                                f"victoriametrics: site-map forces own but foreign unit/config exists at {path}; "
                                "refusing to take over user-owned VictoriaMetrics (exit 2). "
                                "Set serverapps.victoriametrics.mode: inject, or remove the foreign unit."
                            ),
                        )
                    )
                    return plan

    plan.ansible_extra = {
        "site_ns": site_ns,
        "site_dir": str(site_dir.resolve()),
        "serverapp_victoriametrics_home": str(home_path),
        "serverapp_victoriametrics_config_dir": str(config_dir),
        "serverapp_victoriametrics_scrape_path": str(scrape_path),
        "serverapp_victoriametrics_data_dir": str(data_dir),
        "serverapp_victoriametrics_logs_dir": str(logs_dir),
        "serverapp_victoriametrics_label": label,
        "serverapp_victoriametrics_plist_path": str(plist),
        "serverapp_victoriametrics_health_url": health_url,
        "serverapp_victoriametrics_uid": str(os.getuid()),
        "product_version": product_version or "unknown",
    }

    if plist.is_file():
        plan.actions.append(
            PlannedAction(
                app="victoriametrics",
                kind="skip",
                target=str(plist),
                detail=f"launchd plist {label}",
            )
        )
    else:
        plan.actions.append(
            PlannedAction(
                app="victoriametrics",
                kind="create",
                target=str(plist),
                detail=f"launchd plist {label}",
            )
        )
    plan.actions.append(
        PlannedAction(
            app="victoriametrics",
            kind="create" if not scrape_path.is_file() else "skip",
            target=str(scrape_path),
            detail="own-mode scrape.yml",
        )
    )
    plan.actions.append(
        PlannedAction(
            app="victoriametrics",
            kind="ansible",
            target="serverapp_victoriametrics",
            detail="brew (if absent) + bootstrap + health on 8428",
        )
    )
    return plan


def plan_grafana(
    *,
    site_dir: Path,
    site_map: SiteMap,
    site_ns: str,
    force_generated: bool,
    home: Path | None = None,
    product_version: str | None = None,
) -> AppPlan:
    """Build the plan for the grafana adapter.

    Own mode: brew-if-absent, grafana.ini under site_ns, provisioning from
    generated/stayturgid/fragments/grafana/. Inject: drop product fragments
    into the user's provisioning dirs (site-map fragment_dir), or refuse when
    missing include/fragment_dir.
    """
    mode, source = resolve_app_mode("grafana", site_map=site_map, site_ns=site_ns, home=home)
    plan = AppPlan(app="grafana", mode=mode, source=source)
    home_path = home if home is not None else Path.home()
    config_dir = home_path / ".config" / site_ns / "grafana"
    ini_path = config_dir / "grafana.ini"
    logs_dir = home_path / ".config" / site_ns / "logs"
    label = f"com.{site_ns}.grafana"
    plist = home_path / "Library" / "LaunchAgents" / f"{label}.plist"
    health_url = "http://127.0.0.1:3000/api/health"
    provisioning = site_dir / "generated" / PRODUCT / "fragments" / "grafana"
    ds_src = provisioning / "datasources" / "stayturgid.yaml"

    if mode == "off":
        plan.actions.append(
            PlannedAction(
                app="grafana",
                kind="noop",
                target="-",
                detail="mode=off; grafana not activated",
            )
        )
        return plan

    if mode == "inject":
        app_map = site_map.serverapps.get("grafana")
        fragment_dir = app_map.fragment_dir if app_map and app_map.fragment_dir else None
        if fragment_dir is None:
            plan.refusals.append(
                Refusal(
                    kind="missing_include",
                    message=(
                        "grafana: inject mode requires serverapps.grafana.fragment_dir "
                        "(provisioning root or product subdir under dashboards+datasources). "
                        "Set fragment_dir in site-map.yml, or use mode: own."
                    ),
                )
            )
            plan.actions.append(
                PlannedAction(
                    app="grafana",
                    kind="verify",
                    target="fragment_dir",
                    detail="missing fragment_dir → exit 2",
                )
            )
            return plan
        if not ds_src.is_file():
            raise ServerAppsError(
                "grafana inject mode requires rendered fragments under "
                f"generated/{PRODUCT}/fragments/grafana/ — run `just site-sync` first"
            )
        # Copy datasources + dashboard provider into user's provisioning tree.
        for rel in (
            Path("datasources") / "stayturgid.yaml",
            Path("dashboards") / "provider.yaml",
        ):
            src = provisioning / rel
            if not src.is_file():
                continue
            dest = fragment_dir / rel
            plan.inject_copies.append((src, dest))
            if not dest.exists():
                plan.actions.append(
                    PlannedAction(app="grafana", kind="create", target=str(dest), detail="inject fragment copy")
                )
            elif dest.read_bytes() == src.read_bytes():
                plan.actions.append(
                    PlannedAction(app="grafana", kind="skip", target=str(dest), detail="inject fragment identical")
                )
            elif _has_generated_header(dest):
                if force_generated:
                    plan.actions.append(
                        PlannedAction(
                            app="grafana",
                            kind="overwrite",
                            target=str(dest),
                            detail="inject fragment overwrite (--force-generated)",
                        )
                    )
                else:
                    plan.refusals.append(
                        Refusal(
                            kind="drifted",
                            message=(
                                f"grafana: drifted placed fragment {dest} (hand-edited); "
                                "re-run with --force-generated to overwrite product-placed files only"
                            ),
                        )
                    )
                    plan.actions.append(
                        PlannedAction(
                            app="grafana",
                            kind="overwrite",
                            target=str(dest),
                            detail="drifted → exit 2 without --force-generated",
                        )
                    )
            else:
                plan.refusals.append(
                    Refusal(
                        kind="user_owned",
                        message=f"grafana: refusing to overwrite user-owned file at inject destination {dest}",
                    )
                )
                plan.actions.append(
                    PlannedAction(
                        app="grafana",
                        kind="overwrite",
                        target=str(dest),
                        detail="user-owned → exit 2",
                    )
                )
        plan.actions.append(
            PlannedAction(
                app="grafana",
                kind="verify",
                target=health_url,
                detail="inject: product provisioning fragments only (daemon untouched)",
            )
        )
        return plan

    # own mode — require rendered provisioning fragments
    if not (provisioning / "datasources").is_dir():
        raise ServerAppsError(
            "grafana own mode requires rendered fragments under "
            f"generated/{PRODUCT}/fragments/grafana/ — run `just site-sync` first"
        )

    public_host = load_caddy_public_hostname(site_dir, site_map)
    # Choice E (D7-ROUTES-E): serve Grafana under https://<host>/grafana/ when
    # the site declares caddy_public_hostname; otherwise keep loopback defaults.
    if public_host:
        grafana_domain = public_host
        grafana_root_url = f"https://{public_host}/grafana/"
        grafana_sub_path = True
    else:
        grafana_domain = "localhost"
        grafana_root_url = "http://127.0.0.1:3000/"
        grafana_sub_path = False

    plan.ansible_extra = {
        "site_ns": site_ns,
        "site_dir": str(site_dir.resolve()),
        "serverapp_grafana_home": str(home_path),
        "serverapp_grafana_config_dir": str(config_dir),
        "serverapp_grafana_ini_path": str(ini_path),
        "serverapp_grafana_data_dir": str(config_dir / "data"),
        "serverapp_grafana_logs_dir": str(logs_dir),
        "serverapp_grafana_plugins_dir": str(config_dir / "plugins"),
        "serverapp_grafana_provisioning_dir": str(provisioning.resolve()),
        "serverapp_grafana_label": label,
        "serverapp_grafana_plist_path": str(plist),
        "serverapp_grafana_health_url": health_url,
        "serverapp_grafana_uid": str(os.getuid()),
        "serverapp_grafana_domain": grafana_domain,
        "serverapp_grafana_root_url": grafana_root_url,
        "serverapp_grafana_serve_from_sub_path": grafana_sub_path,
        "product_version": product_version or "unknown",
    }

    for path, detail in (
        (plist, f"launchd plist {label}"),
        (ini_path, "own-mode grafana.ini"),
    ):
        if path.is_file():
            plan.actions.append(PlannedAction(app="grafana", kind="skip", target=str(path), detail=detail))
        else:
            plan.actions.append(PlannedAction(app="grafana", kind="create", target=str(path), detail=detail))
    plan.actions.append(
        PlannedAction(
            app="grafana",
            kind="verify",
            target=str(provisioning),
            detail="provisioning from generated/stayturgid/fragments/grafana",
        )
    )
    plan.actions.append(
        PlannedAction(
            app="grafana",
            kind="ansible",
            target="serverapp_grafana",
            detail="brew (if absent) + bootstrap + health on 3000",
        )
    )
    return plan


def plan_olivetin(
    *,
    site_dir: Path,
    site_map: SiteMap,
    site_ns: str,
    force_generated: bool,
    home: Path | None = None,
    product_version: str | None = None,
) -> AppPlan:
    """Build the plan for the olivetin adapter.

    Own mode: binary if absent, minimal config.yaml (projection bootstrap),
    site-namespace unit on 1337. Full inventory→actions projection is D6.
    Inject is not supported (config is a projection, single writer).
    """
    del force_generated
    mode, source = resolve_app_mode("olivetin", site_map=site_map, site_ns=site_ns, home=home)
    plan = AppPlan(app="olivetin", mode=mode, source=source)
    home_path = home if home is not None else Path.home()
    config_dir = home_path / ".config" / site_ns / "olivetin"
    config_path = config_dir / "config.yaml"
    logs_dir = home_path / ".config" / site_ns / "logs"
    install_dir = home_path / ".local" / "share" / "olivetin"
    bin_path = install_dir / "OliveTin"
    webui_dir = install_dir / "webui"
    label = f"com.{site_ns}.olivetin"
    plist = home_path / "Library" / "LaunchAgents" / f"{label}.plist"
    health_url = "http://127.0.0.1:1337/"
    actions_frag = site_dir / "generated" / PRODUCT / "fragments" / "olivetin" / "stayturgid_actions.yaml"

    if mode == "off":
        plan.actions.append(
            PlannedAction(
                app="olivetin",
                kind="noop",
                target="-",
                detail="mode=off; olivetin not activated",
            )
        )
        return plan

    if mode == "inject":
        plan.actions.append(
            PlannedAction(
                app="olivetin",
                kind="noop",
                target=health_url,
                detail="inject not supported for olivetin (config is a projection); use own or off",
            )
        )
        plan.refusals.append(
            Refusal(
                kind="unsupported_mode",
                message=(
                    "olivetin: inject mode is not supported (config is a projection / single writer). "
                    "Set serverapps.olivetin.mode: own or off. Product actions live under "
                    f"generated/{PRODUCT}/fragments/olivetin/ (D6 merges into live config)."
                ),
            )
        )
        return plan

    plan.ansible_extra = {
        "site_ns": site_ns,
        "site_dir": str(site_dir.resolve()),
        "serverapp_olivetin_home": str(home_path),
        "serverapp_olivetin_config_dir": str(config_dir),
        "serverapp_olivetin_config_path": str(config_path),
        "serverapp_olivetin_logs_dir": str(logs_dir),
        "serverapp_olivetin_install_dir": str(install_dir),
        "serverapp_olivetin_bin_path": str(bin_path),
        "serverapp_olivetin_webui_dir": str(webui_dir),
        "serverapp_olivetin_label": label,
        "serverapp_olivetin_plist_path": str(plist),
        "serverapp_olivetin_health_url": health_url,
        "serverapp_olivetin_uid": str(os.getuid()),
        "product_version": product_version or "unknown",
    }

    for path, detail in (
        (plist, f"launchd plist {label}"),
        (config_path, "own-mode config.yaml (D5 empty-actions bootstrap; D6 projection)"),
    ):
        if path.is_file():
            plan.actions.append(PlannedAction(app="olivetin", kind="skip", target=str(path), detail=detail))
        else:
            plan.actions.append(PlannedAction(app="olivetin", kind="create", target=str(path), detail=detail))
    plan.actions.append(
        PlannedAction(
            app="olivetin",
            kind="verify",
            target=str(actions_frag),
            detail="product actions fragment (projection input for D6)",
        )
    )
    plan.actions.append(
        PlannedAction(
            app="olivetin",
            kind="ansible",
            target="serverapp_olivetin",
            detail="binary (if absent) + bootstrap + health on 1337",
        )
    )
    return plan


def plan_landing(
    *,
    site_dir: Path,
    site_map: SiteMap,
    site_ns: str,
    force_generated: bool,
    home: Path | None = None,
    product_root: Path | None = None,
) -> AppPlan:
    """Build the plan for the landing adapter (product-internal; §5.3).

    Own mode manages both LaunchAgents: ``com.<site_ns>.landing`` (HTTP
    server on 8088) and ``com.<site_ns>.landing-discover`` (periodic scan).
    Inject is not meaningful for this product-internal app — treated as off
    with a verify note if forced via site-map.
    """
    del force_generated
    mode, source = resolve_app_mode("landing", site_map=site_map, site_ns=site_ns, home=home)
    plan = AppPlan(app="landing", mode=mode, source=source)
    home_path = home if home is not None else Path.home()
    logs_dir = home_path / ".config" / site_ns / "logs"
    label = f"com.{site_ns}.landing"
    discover_label = f"com.{site_ns}.landing-discover"
    plist = home_path / "Library" / "LaunchAgents" / f"{label}.plist"
    discover_plist = home_path / "Library" / "LaunchAgents" / f"{discover_label}.plist"
    health_url = "http://127.0.0.1:8088/health"
    repo_root = (product_root or REPO_ROOT).resolve()

    if mode == "off":
        plan.actions.append(
            PlannedAction(
                app="landing",
                kind="noop",
                target="-",
                detail="mode=off; landing + landing-discover not activated",
            )
        )
        return plan

    if mode == "inject":
        # Product-internal (§5.3): inject is not a real mode — refuse to manage.
        plan.actions.append(
            PlannedAction(
                app="landing",
                kind="noop",
                target=health_url,
                detail="inject not supported for landing (product-internal); use own or off",
            )
        )
        plan.refusals.append(
            Refusal(
                kind="unsupported_mode",
                message=(
                    "landing: inject mode is not supported (product-internal own-mode app). "
                    "Set serverapps.landing.mode: own or off."
                ),
            )
        )
        return plan

    # own mode
    plan.ansible_extra = {
        "site_ns": site_ns,
        "site_dir": str(site_dir.resolve()),
        "serverapp_landing_home": str(home_path),
        "serverapp_landing_logs_dir": str(logs_dir),
        "serverapp_landing_label": label,
        "serverapp_landing_discover_label": discover_label,
        "serverapp_landing_plist_path": str(plist),
        "serverapp_landing_discover_plist_path": str(discover_plist),
        "serverapp_landing_repo_root": str(repo_root),
        "serverapp_landing_health_url": health_url,
        "serverapp_landing_port": "8088",
        "serverapp_landing_uid": str(os.getuid()),
    }

    for path, detail in (
        (plist, f"launchd plist {label}"),
        (discover_plist, f"launchd plist {discover_label}"),
    ):
        if path.is_file():
            plan.actions.append(PlannedAction(app="landing", kind="skip", target=str(path), detail=detail))
        else:
            plan.actions.append(PlannedAction(app="landing", kind="create", target=str(path), detail=detail))
    plan.actions.append(
        PlannedAction(
            app="landing",
            kind="ansible",
            target="serverapp_landing",
            detail="landing + discover plists + bootstrap + health on 8088",
        )
    )
    return plan


def build_plan(
    *,
    dir_path: str | None = None,
    product_root: Path | None = None,
    env: dict[str, str] | None = None,
    apps: Sequence[str] | None = None,
    force_generated: bool = False,
    home: Path | None = None,
) -> ServerAppsPlan:
    """Compute the full serverapps plan without writing anything."""
    product = (product_root or REPO_ROOT).resolve()
    try:
        destination = resolve_site_dir(dir_path=dir_path, product_root=product, env=env)
    except SiteSyncError as exc:
        raise ServerAppsError(str(exc), exit_code=exc.exit_code) from exc
    try:
        site_map = load_site_map(site_dir=destination, product_root=product)
    except SiteMapError as exc:
        raise ServerAppsError(str(exc)) from exc

    site_ns = load_site_ns(destination, site_map)
    selected = list(apps) if apps else list(KNOWN_APPS)
    unknown = [a for a in selected if a not in KNOWN_APPS]
    if unknown:
        raise ServerAppsError(f"unknown serverapp(s): {', '.join(unknown)}; known: {', '.join(KNOWN_APPS)}")

    # Own-mode base-config template headers (§1.7); best-effort, cosmetic only.
    try:
        product_version = load_product_version(product)
    except SiteSyncError:
        product_version = None

    planners = {
        "caddy": plan_caddy,
        "vector": plan_vector,
        "openobserve": plan_openobserve,
        "victoriametrics": plan_victoriametrics,
        "grafana": plan_grafana,
        "olivetin": plan_olivetin,
        "landing": plan_landing,
    }
    app_plans: list[AppPlan] = []
    for app in selected:
        planner = planners.get(app)
        if planner is None:  # pragma: no cover - guarded by KNOWN_APPS
            raise ServerAppsError(f"no adapter for {app}")
        kwargs = {
            "site_dir": destination,
            "site_map": site_map,
            "site_ns": site_ns,
            "force_generated": force_generated,
            "home": home,
        }
        if app == "landing":
            kwargs["product_root"] = product
        if app in {"caddy", "vector", "grafana", "olivetin", "victoriametrics"}:
            kwargs["product_version"] = product_version
        app_plans.append(planner(**kwargs))

    return ServerAppsPlan(
        destination=destination,
        product_root=product,
        site_ns=site_ns,
        apps=app_plans,
    )


def format_plan(plan: ServerAppsPlan) -> str:
    """Human-readable plan for dry-run / apply logging."""
    lines: list[str] = []
    for app in plan.apps:
        lines.append(f"{app.app}: mode={app.mode} (source={app.source})")
        for action in app.actions:
            detail = f"  {action.detail}" if action.detail else ""
            lines.append(f"  {action.kind:8} {action.target}{detail}")
    return "\n".join(lines) + ("\n" if lines else "")


def _run_ansible_role(plan: ServerAppsPlan, app: AppPlan, *, dry_run: bool) -> None:
    """Invoke the serverapp_<app> playbook (own mode)."""
    playbook = plan.product_root / "ansible" / "playbooks" / "serverapps" / f"{app.app}.yml"
    if not playbook.is_file():
        raise ServerAppsError(f"{app.app} playbook missing: {playbook}")

    if dry_run:
        return

    cmd = [
        "ansible-playbook",
        "-i",
        "localhost,",
        "-c",
        "local",
        str(playbook),
    ]
    for key, value in app.ansible_extra.items():
        cmd.extend(["-e", f"{key}={value}"])

    try:
        result = subprocess.run(
            cmd,
            cwd=str(plan.product_root),
            check=False,
            capture_output=True,
            text=True,
            env={**os.environ, "ANSIBLE_ROLES_PATH": str(plan.product_root / "ansible" / "roles")},
        )
    except OSError as exc:
        raise ServerAppsError(f"failed to run ansible-playbook: {exc}") from exc

    if result.returncode != 0:
        detail = (result.stderr or result.stdout or "").strip()
        raise ServerAppsError(f"ansible serverapp_{app.app} failed (exit {result.returncode}): {detail[:2000]}")


def apply_plan(
    plan: ServerAppsPlan,
    *,
    force_generated: bool = False,
    dry_run: bool = False,
    skip_ansible: bool = False,
) -> None:
    """Apply planned actions. Refuses on unresolved exit-2 conditions."""
    refusals = plan.refusal_list
    if refusals and not (force_generated and _refusals_recoverable_with_force(refusals)):
        raise ServerAppsError(
            "\n".join(r.message for r in refusals),
            exit_code=EXIT_WOULD_OVERWRITE,
        )

    for app in plan.apps:
        if app.mode == "off":
            for action in app.actions:
                if action.kind == "delete" and not dry_run:
                    path = Path(action.target)
                    if path.is_file() and _has_generated_header(path):
                        path.unlink()
            continue

        if app.mode == "inject":
            if app.refusals and not force_generated:
                raise ServerAppsError(
                    "\n".join(app.refuse_messages),
                    exit_code=EXIT_WOULD_OVERWRITE,
                )
            if app.refusals and force_generated and not _refusals_recoverable_with_force(app.refusals):
                raise ServerAppsError(
                    "\n".join(app.refuse_messages),
                    exit_code=EXIT_WOULD_OVERWRITE,
                )
            for src, dest in app.inject_copies:
                if dry_run:
                    continue
                if dest.exists() and dest.read_bytes() == src.read_bytes():
                    continue
                if dest.exists() and not _has_generated_header(dest) and not force_generated:
                    raise ServerAppsError(
                        f"refusing to overwrite user-owned file: {dest}",
                        exit_code=EXIT_WOULD_OVERWRITE,
                    )
                if (
                    dest.exists()
                    and dest.read_bytes() != src.read_bytes()
                    and _has_generated_header(dest)
                    and not force_generated
                ):
                    raise ServerAppsError(
                        f"drifted placed fragment {dest}; re-run with --force-generated",
                        exit_code=EXIT_WOULD_OVERWRITE,
                    )
                dest.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(src, dest)
            continue

        if app.mode == "own":
            if app.refusals:
                raise ServerAppsError(
                    "\n".join(app.refuse_messages),
                    exit_code=EXIT_WOULD_OVERWRITE,
                )
            if skip_ansible:
                # Test hook: still materialize base config for unit tests without launchd.
                if app.app == "caddy":
                    _materialize_caddy_own_for_tests(plan, app, dry_run=dry_run)
                elif app.app == "vector":
                    _materialize_vector_own_for_tests(plan, app, dry_run=dry_run)
                elif app.app == "openobserve":
                    _materialize_openobserve_own_for_tests(plan, app, dry_run=dry_run)
                elif app.app == "victoriametrics":
                    _materialize_victoriametrics_own_for_tests(plan, app, dry_run=dry_run)
                elif app.app == "grafana":
                    _materialize_grafana_own_for_tests(plan, app, dry_run=dry_run)
                elif app.app == "olivetin":
                    _materialize_olivetin_own_for_tests(plan, app, dry_run=dry_run)
                elif app.app == "landing":
                    _materialize_landing_own_for_tests(plan, app, dry_run=dry_run)
                continue
            _run_ansible_role(plan, app, dry_run=dry_run)


def _render_test_launchd_plist(
    *,
    label: str,
    program_arguments: Sequence[str],
    home: str,
    keep_alive: bool = True,
    start_interval: int | None = None,
    working_directory: str | None = None,
    stdout_path: str | None = None,
    stderr_path: str | None = None,
    extra_env: dict[str, str] | None = None,
) -> str:
    """Render a minimal launchd plist body (S-4: shared by the ``_materialize_*_own_for_tests``
    skip-ansible scaffolding below — NOT the real ``serverapp_*/templates/*.plist.j2`` used by
    own-mode apply; this only stands in for launchd during ``skip_ansible=True`` unit tests).
    """
    args_xml = "\n".join(f"        <string>{a}</string>" for a in program_arguments)
    lifecycle_xml = "    <key>KeepAlive</key>\n    <true/>\n" if keep_alive else ""
    if start_interval is not None:
        lifecycle_xml += f"    <key>StartInterval</key>\n    <integer>{start_interval}</integer>\n"
    extra_xml = ""
    if working_directory is not None:
        extra_xml += f"    <key>WorkingDirectory</key>\n    <string>{working_directory}</string>\n"
    if stdout_path is not None:
        extra_xml += f"    <key>StandardOutPath</key>\n    <string>{stdout_path}</string>\n"
    if stderr_path is not None:
        extra_xml += f"    <key>StandardErrorPath</key>\n    <string>{stderr_path}</string>\n"
    env = {"HOME": home, **(extra_env or {})}
    env_xml = "\n".join(f"        <key>{k}</key>\n        <string>{v}</string>" for k, v in env.items())
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"\n'
        '  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n'
        '<plist version="1.0">\n'
        "<dict>\n"
        "    <key>Label</key>\n"
        f"    <string>{label}</string>\n"
        "    <key>ProgramArguments</key>\n"
        "    <array>\n"
        f"{args_xml}\n"
        "    </array>\n"
        "    <key>RunAtLoad</key>\n"
        "    <true/>\n"
        f"{lifecycle_xml}{extra_xml}"
        "    <key>EnvironmentVariables</key>\n"
        "    <dict>\n"
        f"{env_xml}\n"
        "    </dict>\n"
        "</dict>\n"
        "</plist>\n"
    )


def _materialize_caddy_own_for_tests(plan: ServerAppsPlan, app: AppPlan, *, dry_run: bool) -> None:
    """Write base Caddyfile + plist without ansible (unit-test / dry scaffolding)."""
    if dry_run:
        return
    config_path = Path(app.ansible_extra["serverapp_caddy_config_path"])
    plist_path = Path(app.ansible_extra["serverapp_caddy_plist_path"])
    logs_dir = Path(app.ansible_extra["serverapp_caddy_logs_dir"])
    label = app.ansible_extra["serverapp_caddy_label"]
    fragment_glob = app.ansible_extra["serverapp_caddy_fragment_glob"]
    home = app.ansible_extra["serverapp_caddy_home"]
    product_version = app.ansible_extra["product_version"]
    config_path.parent.mkdir(parents=True, exist_ok=True)
    logs_dir.mkdir(parents=True, exist_ok=True)
    health_port = 8080
    body = (
        f"# GENERATED by stayturgid site-sync — DO NOT EDIT (drift → site-sync exit 2)\n"
        f"# template: ansible/roles/serverapp_caddy/templates/Caddyfile.j2\n"
        f"# product_version: {product_version}\n"
        "{\n"
        "\tauto_https disable_redirects\n"
        "\tadmin off\n"
        "}\n"
        "\n"
        f"http://127.0.0.1:{health_port} {{\n"
        '\trespond /health "OK" 200\n'
        "}\n"
        "\n"
        f"import {fragment_glob}\n"
    )
    config_path.write_text(body, encoding="utf-8")
    plist_path.parent.mkdir(parents=True, exist_ok=True)
    caddy_bin = shutil.which("caddy") or "/opt/homebrew/bin/caddy"
    plist_path.write_text(
        _render_test_launchd_plist(
            label=label,
            program_arguments=[caddy_bin, "run", "--config", str(config_path), "--adapter", "caddyfile"],
            home=home,
            stdout_path=f"{logs_dir}/caddy.log",
            stderr_path=f"{logs_dir}/caddy.log",
        ),
        encoding="utf-8",
    )


def _materialize_vector_own_for_tests(plan: ServerAppsPlan, app: AppPlan, *, dry_run: bool) -> None:
    """Write base vector.yaml + multi-config plist without ansible (unit tests)."""
    if dry_run:
        return
    config_path = Path(app.ansible_extra["serverapp_vector_config_path"])
    data_dir = Path(app.ansible_extra["serverapp_vector_data_dir"])
    plist_path = Path(app.ansible_extra["serverapp_vector_plist_path"])
    logs_dir = Path(app.ansible_extra["serverapp_vector_logs_dir"])
    label = app.ansible_extra["serverapp_vector_label"]
    fragment_csv = app.ansible_extra["serverapp_vector_fragment_configs"]
    home = app.ansible_extra["serverapp_vector_home"]
    product_version = app.ansible_extra["product_version"]
    config_path.parent.mkdir(parents=True, exist_ok=True)
    data_dir.mkdir(parents=True, exist_ok=True)
    logs_dir.mkdir(parents=True, exist_ok=True)
    body = (
        f"# GENERATED by stayturgid site-sync — DO NOT EDIT (drift → site-sync exit 2)\n"
        f"# template: ansible/roles/serverapp_vector/templates/vector.yaml.j2\n"
        f"# product_version: {product_version}\n"
        f'data_dir: "{data_dir}"\n'
        "\n"
        "api:\n"
        "  enabled: true\n"
        '  address: "127.0.0.1:8686"\n'
    )
    config_path.write_text(body, encoding="utf-8")
    plist_path.parent.mkdir(parents=True, exist_ok=True)
    vector_bin = shutil.which("vector") or "/opt/homebrew/bin/vector"
    args = [vector_bin, "--dangerously-allow-env-var-interpolation", "--config", str(config_path)]
    for frag in (p.strip() for p in fragment_csv.split(",") if p.strip()):
        args.extend(["--config", frag])
    plist_path.write_text(
        _render_test_launchd_plist(
            label=label,
            program_arguments=args,
            home=home,
            stdout_path=f"{logs_dir}/vector.log",
            stderr_path=f"{logs_dir}/vector.log",
        ),
        encoding="utf-8",
    )


def _materialize_openobserve_own_for_tests(plan: ServerAppsPlan, app: AppPlan, *, dry_run: bool) -> None:
    """Write openobserve launchd plist without ansible (unit tests)."""
    del plan  # unused; signature matches sibling materializers
    if dry_run:
        return
    plist_path = Path(app.ansible_extra["serverapp_openobserve_plist_path"])
    data_dir = Path(app.ansible_extra["serverapp_openobserve_data_dir"])
    logs_dir = Path(app.ansible_extra["serverapp_openobserve_logs_dir"])
    bin_path = Path(app.ansible_extra["serverapp_openobserve_bin_path"])
    label = app.ansible_extra["serverapp_openobserve_label"]
    home = app.ansible_extra["serverapp_openobserve_home"]
    data_dir.mkdir(parents=True, exist_ok=True)
    (data_dir / "cache").mkdir(parents=True, exist_ok=True)
    logs_dir.mkdir(parents=True, exist_ok=True)
    bin_path.parent.mkdir(parents=True, exist_ok=True)
    plist_path.parent.mkdir(parents=True, exist_ok=True)
    # Placeholder binary for unit tests only (not executed under skip_ansible).
    if not bin_path.is_file():
        bin_path.write_text("#!/bin/sh\n# test stub\n", encoding="utf-8")
        bin_path.chmod(0o755)
    plist_path.write_text(
        _render_test_launchd_plist(
            label=label,
            program_arguments=[str(bin_path)],
            home=home,
            working_directory=str(data_dir),
            stdout_path=f"{logs_dir}/openobserve.log",
            stderr_path=f"{logs_dir}/openobserve.log",
            extra_env={
                "ZO_DATA_DIR_PATH": str(data_dir),
                "ZO_DATA_CACHE_DIR": f"{data_dir}/cache",
                "ZO_HTTP_PORT": "5080",
                "ZO_HTTP_ADDR": "127.0.0.1",
                "ZO_GRPC_ADDR": "127.0.0.1",
            },
        ),
        encoding="utf-8",
    )


def _materialize_victoriametrics_own_for_tests(plan: ServerAppsPlan, app: AppPlan, *, dry_run: bool) -> None:
    """Write scrape.yml + launchd plist without ansible (unit tests)."""
    del plan
    if dry_run:
        return
    scrape_path = Path(app.ansible_extra["serverapp_victoriametrics_scrape_path"])
    data_dir = Path(app.ansible_extra["serverapp_victoriametrics_data_dir"])
    plist_path = Path(app.ansible_extra["serverapp_victoriametrics_plist_path"])
    logs_dir = Path(app.ansible_extra["serverapp_victoriametrics_logs_dir"])
    label = app.ansible_extra["serverapp_victoriametrics_label"]
    home = app.ansible_extra["serverapp_victoriametrics_home"]
    scrape_path.parent.mkdir(parents=True, exist_ok=True)
    data_dir.mkdir(parents=True, exist_ok=True)
    logs_dir.mkdir(parents=True, exist_ok=True)
    scrape_path.write_text(
        "# GENERATED by stayturgid site-sync — DO NOT EDIT (drift → site-sync exit 2)\n"
        "global:\n  scrape_interval: 15s\n"
        "scrape_configs:\n  - job_name: victoriametrics\n"
        '    static_configs:\n      - targets: ["127.0.0.1:8428"]\n',
        encoding="utf-8",
    )
    bin_path = shutil.which("victoria-metrics") or "/opt/homebrew/bin/victoria-metrics"
    plist_path.parent.mkdir(parents=True, exist_ok=True)
    plist_path.write_text(
        _render_test_launchd_plist(
            label=label,
            program_arguments=[
                bin_path,
                "-httpListenAddr=127.0.0.1:8428",
                f"-promscrape.config={scrape_path}",
                f"-storageDataPath={data_dir}",
            ],
            home=home,
            stdout_path=f"{logs_dir}/victoriametrics.log",
        ),
        encoding="utf-8",
    )


def _materialize_grafana_own_for_tests(plan: ServerAppsPlan, app: AppPlan, *, dry_run: bool) -> None:
    """Write grafana.ini + launchd plist without ansible (unit tests)."""
    del plan
    if dry_run:
        return
    ini_path = Path(app.ansible_extra["serverapp_grafana_ini_path"])
    data_dir = Path(app.ansible_extra["serverapp_grafana_data_dir"])
    logs_dir = Path(app.ansible_extra["serverapp_grafana_logs_dir"])
    plugins_dir = Path(app.ansible_extra["serverapp_grafana_plugins_dir"])
    provisioning = app.ansible_extra["serverapp_grafana_provisioning_dir"]
    plist_path = Path(app.ansible_extra["serverapp_grafana_plist_path"])
    label = app.ansible_extra["serverapp_grafana_label"]
    home = app.ansible_extra["serverapp_grafana_home"]
    for path in (ini_path.parent, data_dir, logs_dir, plugins_dir, plist_path.parent):
        path.mkdir(parents=True, exist_ok=True)
    ini_path.write_text(
        "# GENERATED by stayturgid site-sync — DO NOT EDIT (drift → site-sync exit 2)\n"
        f"[paths]\ndata = {data_dir}\nlogs = {logs_dir}\n"
        f"plugins = {plugins_dir}\nprovisioning = {provisioning}\n"
        "[server]\nhttp_addr = 127.0.0.1\nhttp_port = 3000\n",
        encoding="utf-8",
    )
    gf_bin = shutil.which("grafana") or "/opt/homebrew/bin/grafana"
    plist_path.write_text(
        _render_test_launchd_plist(
            label=label,
            program_arguments=[gf_bin, "server", "--config", str(ini_path)],
            home=home,
            stdout_path=f"{logs_dir}/grafana.log",
        ),
        encoding="utf-8",
    )


def _materialize_olivetin_own_for_tests(plan: ServerAppsPlan, app: AppPlan, *, dry_run: bool) -> None:
    """Write config.yaml + launchd plist without ansible (unit tests)."""
    del plan
    if dry_run:
        return
    config_path = Path(app.ansible_extra["serverapp_olivetin_config_path"])
    config_dir = Path(app.ansible_extra["serverapp_olivetin_config_dir"])
    install_dir = Path(app.ansible_extra["serverapp_olivetin_install_dir"])
    bin_path = Path(app.ansible_extra["serverapp_olivetin_bin_path"])
    webui_dir = Path(app.ansible_extra["serverapp_olivetin_webui_dir"])
    plist_path = Path(app.ansible_extra["serverapp_olivetin_plist_path"])
    logs_dir = Path(app.ansible_extra["serverapp_olivetin_logs_dir"])
    label = app.ansible_extra["serverapp_olivetin_label"]
    home = app.ansible_extra["serverapp_olivetin_home"]
    config_dir.mkdir(parents=True, exist_ok=True)
    logs_dir.mkdir(parents=True, exist_ok=True)
    install_dir.mkdir(parents=True, exist_ok=True)
    webui_dir.mkdir(parents=True, exist_ok=True)
    if not bin_path.is_file():
        bin_path.write_text("#!/bin/sh\n# test stub\n", encoding="utf-8")
        bin_path.chmod(0o755)
    config_path.write_text(
        "# GENERATED by stayturgid site-sync — DO NOT EDIT (drift → site-sync exit 2)\n"
        "ListenAddressSingleHTTPFrontend: 127.0.0.1:1337\n"
        f"WebUIDir: {webui_dir}\n"
        "actions: []\n",
        encoding="utf-8",
    )
    plist_path.parent.mkdir(parents=True, exist_ok=True)
    plist_path.write_text(
        _render_test_launchd_plist(
            label=label,
            program_arguments=[str(bin_path), "-configdir", str(config_dir)],
            home=home,
            stdout_path=f"{logs_dir}/olivetin.log",
        ),
        encoding="utf-8",
    )


def _materialize_landing_own_for_tests(plan: ServerAppsPlan, app: AppPlan, *, dry_run: bool) -> None:
    """Write landing + discover plists without ansible (unit tests)."""
    del plan
    if dry_run:
        return
    home = app.ansible_extra["serverapp_landing_home"]
    logs_dir = Path(app.ansible_extra["serverapp_landing_logs_dir"])
    repo = app.ansible_extra["serverapp_landing_repo_root"]
    logs_dir.mkdir(parents=True, exist_ok=True)
    for key, label_key in (
        ("serverapp_landing_plist_path", "serverapp_landing_label"),
        ("serverapp_landing_discover_plist_path", "serverapp_landing_discover_label"),
    ):
        plist_path = Path(app.ansible_extra[key])
        label = app.ansible_extra[label_key]
        plist_path.parent.mkdir(parents=True, exist_ok=True)
        is_discover = "discover" in label
        if is_discover:
            args = ["/opt/homebrew/bin/python3", f"{repo}/control/landing/discover.py"]
            keep_alive = False
            start_interval = 3600
        else:
            args = ["/opt/homebrew/bin/python3", f"{repo}/control/landing/landing.py", "--port", "8088"]
            keep_alive = True
            start_interval = None
        plist_path.write_text(
            _render_test_launchd_plist(
                label=label,
                program_arguments=args,
                home=home,
                keep_alive=keep_alive,
                start_interval=start_interval,
                working_directory=repo,
                stdout_path=f"{logs_dir}/{'landing-discover' if is_discover else 'landing'}.log",
            ),
            encoding="utf-8",
        )


def _parse_mode(value: str) -> Mode:
    mode = value.strip().lower()
    if mode not in {"apply", "dry-run"}:
        raise ServerAppsError(f"mode must be apply or dry-run; got {value!r}")
    return mode  # type: ignore[return-value]


def _parse_bool_flag(value: str | bool | None) -> bool:
    if value is None or value is False:
        return False
    if value is True:
        return True
    text = str(value).strip().lower()
    if text in {"", "0", "false", "no", "off"}:
        return False
    if text in {"1", "true", "yes", "on"}:
        return True
    raise ServerAppsError(f"force-generated must be 0/1 or true/false; got {value!r}")


def _parse_apps(value: str | None) -> list[str] | None:
    if value is None or not str(value).strip():
        return None
    apps = [part.strip() for part in str(value).split(",") if part.strip()]
    return apps or None


def run_site_serverapps(
    *,
    dir_path: str | None = None,
    mode: str = "apply",
    apps: str | Sequence[str] | None = None,
    force_generated: bool | str = False,
    product_root: Path | None = None,
    env: dict[str, str] | None = None,
    home: Path | None = None,
    skip_ansible: bool = False,
    stdout: object | None = None,
    stderr: object | None = None,
) -> int:
    """Programmatic entry point used by tests and ``main``."""
    out = stdout if stdout is not None else sys.stdout
    err = stderr if stderr is not None else sys.stderr
    try:
        parsed_mode = _parse_mode(mode)
        force = _parse_bool_flag(force_generated)
        if isinstance(apps, str) or apps is None:
            app_list = _parse_apps(apps if isinstance(apps, str) else None)
        else:
            app_list = list(apps)

        plan = build_plan(
            dir_path=dir_path,
            product_root=product_root,
            env=env,
            apps=app_list,
            force_generated=force,
            home=home,
        )
        text = format_plan(plan)
        print(text, end="", file=out)

        refusals = plan.refusal_list
        if refusals and not (force and _refusals_recoverable_with_force(refusals)):
            print(f"error: {chr(10).join(r.message for r in refusals)}", file=err)
            return EXIT_WOULD_OVERWRITE

        if parsed_mode == "dry-run":
            return EXIT_OK

        apply_plan(plan, force_generated=force, dry_run=False, skip_ansible=skip_ansible)
        # Summarize
        for app in plan.apps:
            kinds = [a.kind for a in app.actions]
            print(
                f"site-serverapps: {app.app} mode={app.mode} source={app.source} "
                f"actions={','.join(kinds) if kinds else 'none'}",
                file=err,
            )
        return EXIT_OK
    except ServerAppsError as exc:
        print(f"error: {exc}", file=err)
        return exc.exit_code
    except SiteSyncError as exc:
        print(f"error: {exc}", file=err)
        return exc.exit_code
    except OSError as exc:
        print(f"error: {exc}", file=err)
        return EXIT_PRECONDITION


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Activate stayturgid serverapp adapters for a site overlay (Site Contract v1 §5).",
    )
    parser.add_argument("--dir", dest="dir_path", default="", help="explicit site directory")
    parser.add_argument("--mode", default="apply", help="apply (default) or dry-run")
    parser.add_argument(
        "--apps",
        default="",
        help="comma-separated app list (default: all known apps)",
    )
    parser.add_argument(
        "--force-generated",
        action="store_true",
        default=False,
        help="overwrite drifted product-placed inject fragments only",
    )
    parser.add_argument(
        "assignments",
        nargs="*",
        help="optional KEY=VALUE: dir=, mode=, apps=, force-generated=",
    )
    return parser


def _merge_assignments(
    *,
    dir_path: str,
    mode: str,
    apps: str,
    force_generated: bool,
    assignments: Sequence[str],
) -> tuple[str, str, str, bool]:
    allowed = {"dir", "mode", "apps", "force-generated"}
    values: dict[str, str] = {
        "dir": dir_path,
        "mode": mode,
        "apps": apps,
        "force-generated": "1" if force_generated else "0",
    }
    for token in assignments:
        if "=" not in token:
            raise ServerAppsError(f"unknown argument {token!r}; expected dir= / mode= / apps= / force-generated=")
        key, value = token.split("=", 1)
        if key not in allowed:
            raise ServerAppsError(f"unknown assignment {key!r}; expected one of: {', '.join(sorted(allowed))}")
        values[key] = value
    return values["dir"], values["mode"], values["apps"], _parse_bool_flag(values["force-generated"])


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_arg_parser()
    args = parser.parse_args(list(argv) if argv is not None else None)
    try:
        dir_path, mode, apps, force = _merge_assignments(
            dir_path=args.dir_path,
            mode=args.mode,
            apps=args.apps,
            force_generated=args.force_generated,
            assignments=args.assignments,
        )
    except ServerAppsError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return exc.exit_code
    return run_site_serverapps(
        dir_path=dir_path or None,
        mode=mode,
        apps=apps or None,
        force_generated=force,
    )


if __name__ == "__main__":
    raise SystemExit(main())
