"""Phase D6 tests: pure inventory→fragment projections + OliveTin single-writer merge.

Covers the step2 plan row D6 checklist: pure re-render no-op, closed write
set refusal, host add/remove rewriting only the closed set, and OliveTin
action-id collision / prefix violations exiting 1 (foreign live config → 2).
"""

from __future__ import annotations

import io
import sys
import textwrap
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from control.site_contract import olivetin_projection as op  # noqa: E402
from control.site_contract import site_init as si  # noqa: E402
from control.site_contract import site_sync as ss  # noqa: E402

FIXED_VERSION = "9.9.9-test"
FIXED_COMMIT = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
FIXED_SYNCED = "2026-07-19T12:00:00Z"

GENERATED = "generated/stayturgid"
CLOSED_SET = {
    f"{GENERATED}/fragments/caddy/stayturgid.caddy",
    f"{GENERATED}/fragments/grafana/datasources/stayturgid.yaml",
    f"{GENERATED}/fragments/grafana/dashboards/provider.yaml",
    f"{GENERATED}/fragments/grafana/dashboards/json/stayturgid-fleet.json",
    f"{GENERATED}/fragments/olivetin/stayturgid_actions.yaml",
    f"{GENERATED}/.lockfile.yml",
}
OLIVETIN_FRAGMENT = f"{GENERATED}/fragments/olivetin/stayturgid_actions.yaml"
DASHBOARD_JSON = f"{GENERATED}/fragments/grafana/dashboards/json/stayturgid-fleet.json"

LIVE_HEADER = "# GENERATED by stayturgid site-sync — DO NOT EDIT (single-writer projection)\n# bootstrap placeholder\n"


def _init_site(tmp_path: Path, name: str = "example") -> Path:
    dest = tmp_path / f"site-{name}"
    err = io.StringIO()
    code = si.run_site_init(
        sitename=name,
        dir_path=str(dest),
        mode="apply",
        product_root=ROOT,
        env={},
        stdout=io.StringIO(),
        stderr=err,
    )
    assert code == si.EXIT_OK, err.getvalue()
    return dest


def _write_inventory(site: Path, host_names: list[str]) -> None:
    hosts = {
        name: {"ansible_host": f"100.0.0.{10 + index}", "device_label": f"Device {name}"}
        for index, name in enumerate(host_names)
    }
    doc = {"all": {"children": {"stayturgid": {"hosts": hosts}}}}
    (site / "inventory" / "hosts.yml").write_text(yaml.safe_dump(doc), encoding="utf-8")


def _enable_site_ns(site: Path, ns: str = "example") -> None:
    group_vars = site / "inventory" / "group_vars"
    group_vars.mkdir(parents=True, exist_ok=True)
    (group_vars / "all.yml").write_text(f"site_ns: {ns}\n", encoding="utf-8")


def _live_config_path(home: Path, ns: str = "example") -> Path:
    return home / ".config" / ns / "olivetin" / "config.yaml"


def _seed_live_config(home: Path, ns: str = "example", content: str | None = None) -> Path:
    live = _live_config_path(home, ns)
    live.parent.mkdir(parents=True, exist_ok=True)
    live.write_text(content if content is not None else LIVE_HEADER + "actions: []\n", encoding="utf-8")
    return live


def _sync(
    site: Path,
    home: Path,
    *,
    mode: str = "apply",
    commit: str = FIXED_COMMIT,
    manifest_path: Path | None = None,
) -> tuple[int, str, str]:
    out = io.StringIO()
    err = io.StringIO()
    code = ss.run_site_sync(
        dir_path=str(site),
        mode=mode,
        product_root=ROOT,
        env={},
        manifest_path=manifest_path,
        product_version=FIXED_VERSION,
        product_commit=commit,
        synced=FIXED_SYNCED,
        stdout=out,
        stderr=err,
        home=home,
    )
    return code, out.getvalue(), err.getvalue()


def _actions_map(stdout: str) -> dict[str, str]:
    actions: dict[str, str] = {}
    for line in stdout.splitlines():
        if not line.strip():
            continue
        parts = line.split(maxsplit=1)
        actions[parts[1]] = parts[0]
    return actions


def _snapshot_files(root: Path) -> dict[str, bytes]:
    if not root.exists():
        return {}
    return {p.relative_to(root).as_posix(): p.read_bytes() for p in sorted(root.rglob("*")) if p.is_file()}


# ── Purity ──────────────────────────────────────────────────────────────────


def test_pure_rerender_is_byte_identical_and_second_apply_noop(tmp_path: Path) -> None:
    site = _init_site(tmp_path)
    home = tmp_path / "home"
    _write_inventory(site, ["zeta", "alpha", "mid"])

    code, _, err = _sync(site, home)
    assert code == 0, err
    first = _snapshot_files(site / GENERATED)

    code, out, err = _sync(site, home, mode="dry-run")
    assert code == 0, err
    assert set(_actions_map(out).values()) == {"skip"}, out

    code, _, err = _sync(site, home)
    assert code == 0, err
    assert _snapshot_files(site / GENERATED) == first


def test_hosts_render_sorted_by_name_regardless_of_inventory_order(tmp_path: Path) -> None:
    site = _init_site(tmp_path)
    home = tmp_path / "home"
    _write_inventory(site, ["zeta", "alpha", "mid"])
    code, _, err = _sync(site, home)
    assert code == 0, err

    fragment = yaml.safe_load((site / OLIVETIN_FRAGMENT).read_text(encoding="utf-8"))
    deploy_ids = [a["id"] for a in fragment["actions"] if a["id"].startswith("stayturgid_deploy_")]
    assert deploy_ids == ["stayturgid_deploy_alpha", "stayturgid_deploy_mid", "stayturgid_deploy_zeta"]

    import json

    dashboard = json.loads((site / DASHBOARD_JSON).read_text(encoding="utf-8"))
    host_panels = [p for p in dashboard["panels"] if p["id"] >= 100]
    assert [p["id"] for p in host_panels] == [100, 101, 102]
    assert [p["title"] for p in host_panels] == [
        "Device alpha (alpha)",
        "Device mid (mid)",
        "Device zeta (zeta)",
    ]
    assert all(t["datasource"]["uid"] == "stayturgid-victoriametrics" for p in host_panels for t in p["targets"])


# ── Closed write set ────────────────────────────────────────────────────────


def test_host_add_and_remove_rewrite_only_closed_set(tmp_path: Path) -> None:
    site = _init_site(tmp_path)
    home = tmp_path / "home"
    _write_inventory(site, ["alpha", "mid"])
    code, _, err = _sync(site, home)
    assert code == 0, err

    _write_inventory(site, ["alpha", "mid", "new-host"])
    code, out, err = _sync(site, home, mode="dry-run")
    assert code == 0, err
    changed = {path for path, action in _actions_map(out).items() if action != "skip"}
    assert changed, out
    assert changed <= CLOSED_SET, f"outside closed set: {changed - CLOSED_SET}"

    code, _, err = _sync(site, home)
    assert code == 0, err
    assert "stayturgid_deploy_new_host" in (site / OLIVETIN_FRAGMENT).read_text(encoding="utf-8")

    _write_inventory(site, ["alpha", "mid"])
    code, out, err = _sync(site, home, mode="dry-run")
    assert code == 0, err
    changed = {path for path, action in _actions_map(out).items() if action != "skip"}
    assert changed
    assert changed <= CLOSED_SET, f"outside closed set: {changed - CLOSED_SET}"


def test_inventory_consuming_template_outside_closed_set_refused(tmp_path: Path) -> None:
    site = _init_site(tmp_path)
    home = tmp_path / "home"
    manifest = tmp_path / "manifest.yml"
    manifest.write_text(
        textwrap.dedent(
            """\
            contract_version: 1
            product: stayturgid
            files:
              - path: generated/stayturgid/notes.txt
                template: fragments/olivetin/stayturgid_actions.yaml.j2
            """
        ),
        encoding="utf-8",
    )
    code, _, err = _sync(site, home, manifest_path=manifest)
    assert code == 1
    assert "closed write set" in err
    assert not (site / "generated" / "stayturgid" / "notes.txt").exists()


# ── OliveTin single-writer merge ────────────────────────────────────────────


def test_projection_overwrites_live_config_and_writes_nothing_else(tmp_path: Path) -> None:
    site = _init_site(tmp_path)
    home = tmp_path / "home"
    _write_inventory(site, ["alpha"])
    _enable_site_ns(site)
    _seed_live_config(home)

    code, _, err = _sync(site, home)
    assert code == 0, err
    assert "olivetin projection: overwrite" in err

    live = _live_config_path(home)
    doc = yaml.safe_load(live.read_text(encoding="utf-8"))
    assert doc["ListenAddressSingleHTTPFrontend"] == "127.0.0.1:1337"
    assert doc["pageTitle"] == "Stayturgid Fleet Control"
    ids = [a["id"] for a in doc["actions"]]
    assert "stayturgid_fleet_health" in ids
    assert "stayturgid_deploy_alpha" in ids
    head = live.read_text(encoding="utf-8").splitlines()[:3]
    assert any("GENERATED by stayturgid" in line for line in head)
    # Single-writer write set: exactly the one live file under home.
    assert set(_snapshot_files(home)) == {live.relative_to(home).as_posix()}

    # Second apply: projection skip, live bytes unchanged.
    before = live.read_bytes()
    code, _, err = _sync(site, home)
    assert code == 0, err
    assert "olivetin projection: skip" in err
    assert live.read_bytes() == before


def test_projection_dry_run_lists_live_config_action_without_writing(tmp_path: Path) -> None:
    site = _init_site(tmp_path)
    home = tmp_path / "home"
    _write_inventory(site, ["alpha"])
    _enable_site_ns(site)
    live = _seed_live_config(home)
    before = live.read_bytes()

    code, out, err = _sync(site, home, mode="dry-run")
    assert code == 0, err
    assert "(olivetin projection)" in out
    assert f"overwrite {live}" in out
    assert live.read_bytes() == before


def test_projection_merges_user_actions_after_product_actions(tmp_path: Path) -> None:
    site = _init_site(tmp_path)
    home = tmp_path / "home"
    _write_inventory(site, ["alpha"])
    _enable_site_ns(site)
    _seed_live_config(home)
    user_dir = site / "olivetin"
    user_dir.mkdir()
    user_file = user_dir / "user-actions.yaml"
    user_file.write_text(
        "actions:\n  - id: user_reboot_router\n    title: Reboot router\n    shell: echo hi\n",
        encoding="utf-8",
    )
    user_before = user_file.read_bytes()

    code, _, err = _sync(site, home)
    assert code == 0, err
    doc = yaml.safe_load(_live_config_path(home).read_text(encoding="utf-8"))
    ids = [a["id"] for a in doc["actions"]]
    assert ids[-1] == "user_reboot_router"
    assert all(i.startswith("stayturgid_") for i in ids[:-1])
    # User file is input only — never modified.
    assert user_file.read_bytes() == user_before


def test_projection_user_bad_prefix_exits_1_and_writes_nothing(tmp_path: Path) -> None:
    site = _init_site(tmp_path)
    home = tmp_path / "home"
    _write_inventory(site, ["alpha"])
    _enable_site_ns(site)
    live = _seed_live_config(home)
    before = live.read_bytes()
    (site / "olivetin").mkdir()
    (site / "olivetin" / "user-actions.yaml").write_text(
        "actions:\n  - id: stayturgid_fake\n    shell: echo boo\n", encoding="utf-8"
    )

    code, _, err = _sync(site, home)
    assert code == 1
    assert "user_" in err
    assert live.read_bytes() == before
    # Plan-then-act: refusal happens before fragment writes.
    assert not (site / OLIVETIN_FRAGMENT).exists()
    assert not (site / GENERATED / ".lockfile.yml").exists()


def test_projection_duplicate_id_exits_1(tmp_path: Path) -> None:
    site = _init_site(tmp_path)
    home = tmp_path / "home"
    _write_inventory(site, ["alpha"])
    _enable_site_ns(site)
    _seed_live_config(home)
    (site / "olivetin").mkdir()
    (site / "olivetin" / "user-actions.yaml").write_text(
        "actions:\n  - id: user_x\n    shell: echo a\n  - id: user_x\n    shell: echo b\n",
        encoding="utf-8",
    )

    code, _, err = _sync(site, home)
    assert code == 1
    assert "duplicate" in err


def test_projection_foreign_live_config_exits_2_untouched(tmp_path: Path) -> None:
    site = _init_site(tmp_path)
    home = tmp_path / "home"
    _write_inventory(site, ["alpha"])
    _enable_site_ns(site)
    live = _seed_live_config(home, content="# my hand-rolled olivetin config\nactions: []\n")
    before = live.read_bytes()

    code, _, err = _sync(site, home)
    assert code == 2
    assert "foreign" in err
    assert live.read_bytes() == before
    assert not (site / OLIVETIN_FRAGMENT).exists()
    assert not (site / GENERATED / ".lockfile.yml").exists()


def test_projection_skips_when_live_config_absent_or_site_ns_missing(tmp_path: Path) -> None:
    site = _init_site(tmp_path)
    home = tmp_path / "home"
    _write_inventory(site, ["alpha"])
    _enable_site_ns(site)
    code, _, err = _sync(site, home)  # no live config seeded
    assert code == 0, err
    assert "olivetin projection" not in err
    assert not _live_config_path(home).exists()

    site2 = _init_site(tmp_path, name="nons")
    home2 = tmp_path / "home2"
    _write_inventory(site2, ["alpha"])  # no site_ns fact
    code, _, err = _sync(site2, home2)
    assert code == 0, err
    assert "olivetin projection" not in err


def test_projection_missing_registry_port_exits_1(tmp_path: Path) -> None:
    site = _init_site(tmp_path)
    home = tmp_path / "home"
    _write_inventory(site, ["alpha"])
    _enable_site_ns(site)
    _seed_live_config(home)
    ports = site / "registry" / "ports.yml"
    doc = yaml.safe_load(ports.read_text(encoding="utf-8"))
    for entries in doc.get("product_defaults", {}).values():
        entries[:] = [e for e in entries if e.get("service") != "olivetin"]
    ports.write_text(yaml.safe_dump(doc), encoding="utf-8")

    # The fragment templates themselves reference ports['olivetin'], so the
    # unregistered port fails loudly at render time (StrictUndefined → exit 1)
    # before the projection's own port check.
    code, _, err = _sync(site, home)
    assert code == 1
    assert "olivetin" in err


# ── merge_config unit behavior ──────────────────────────────────────────────


def test_merge_config_deterministic_and_stable_key_order() -> None:
    fragment = "actions:\n  - id: stayturgid_a\n    shell: echo a\n"
    user = "actions:\n  - id: user_b\n    shell: echo b\n"
    kwargs: dict[str, Any] = dict(
        fragment_text=fragment,
        user_text=user,
        listen_address="127.0.0.1:1337",
        webui_dir="/tmp/webui",
        product_version="1.0.0",
        product_commit="c" * 40,
    )
    one = op.merge_config(**kwargs)
    two = op.merge_config(**kwargs)
    assert one == two
    body = yaml.safe_load(one.decode("utf-8"))
    assert list(body) == ["ListenAddressSingleHTTPFrontend", "WebUIDir", "pageTitle", "actions"]
    assert [a["id"] for a in body["actions"]] == ["stayturgid_a", "user_b"]


def test_merge_config_rejects_missing_or_malformed_ids() -> None:
    import pytest

    with pytest.raises(ValueError, match="missing a string 'id'"):
        op.merge_config(
            fragment_text="actions:\n  - shell: echo a\n",
            user_text=None,
            listen_address="127.0.0.1:1337",
            webui_dir="/tmp/webui",
            product_version="1",
            product_commit="c",
        )
    with pytest.raises(ValueError, match="must match"):
        op.merge_config(
            fragment_text='actions:\n  - id: "Stayturgid Bad"\n    shell: echo a\n',
            user_text=None,
            listen_address="127.0.0.1:1337",
            webui_dir="/tmp/webui",
            product_version="1",
            product_commit="c",
        )
