#!/usr/bin/env python3
"""Install Shizuku ``rish`` into Termux (~/.stayturgid/bin).

Extracts ``rish_shizuku.dex`` from the installed Shizuku APK and writes a
wrapper that loads it via ``app_process``. Default fleet deploy runs
``install``. On Fire OS, Termux↔Shizuku binder often times out — rish is
still installed for stock-Android helpers and future OEM fixes.

Usage:
  stayturgid_rish.py install|status|which
"""
from __future__ import annotations

import os
import subprocess
import sys
import zipfile

HOME = os.environ.get("HOME", "/data/data/com.termux/files/home")
STG = os.path.join(HOME, ".stayturgid")
BIN = os.path.join(STG, "bin")
RISH_DIR = os.path.join(STG, "lib", "rish")
DEX_NAME = "rish_shizuku.dex"
WRAPPER = os.path.join(BIN, "rish")
SHIZUKU_PKG = os.environ.get(
    "STAYTURGID_SHIZUKU_PACKAGE", "moe.shizuku.privileged.api"
)

_WRAPPER_BODY = """#!/system/bin/sh
# Generated by stayturgid_rish.py — do not hand-edit.
BASEDIR="{rish_dir}"
DEX="$BASEDIR/{dex}"
if [ ! -f "$DEX" ]; then
  echo "Cannot find $DEX — run stayturgid_rish.py install" >&2
  exit 1
fi
[ -z "$RISH_APPLICATION_ID" ] && export RISH_APPLICATION_ID="com.termux"
[ -z "$MANAGER_APPLICATION_ID" ] && export MANAGER_APPLICATION_ID="{pkg}"
exec /system/bin/app_process -Djava.class.path="$DEX" /system/bin \\
  --nice-name=rish rikka.shizuku.shell.ShizukuShellLoader "$@"
"""


def _run(args: list[str], timeout: float = 30) -> subprocess.CompletedProcess:
    return subprocess.run(
        args, capture_output=True, text=True, timeout=timeout
    )


def shizuku_apk_path() -> str | None:
    r = _run(["pm", "path", SHIZUKU_PKG], timeout=15)
    if r.returncode != 0:
        return None
    for line in (r.stdout or "").splitlines():
        line = line.strip().replace("\r", "")
        if line.startswith("package:"):
            path = line.split(":", 1)[1]
            if path and os.path.isfile(path):
                return path
    return None


def installed() -> bool:
    dex = os.path.join(RISH_DIR, DEX_NAME)
    return os.path.isfile(WRAPPER) and os.path.isfile(dex) and os.access(WRAPPER, os.X_OK)


def install(*, force: bool = False) -> str:
    """Extract dex + write wrapper. Returns path to ``rish`` wrapper."""
    if installed() and not force:
        return WRAPPER
    apk = shizuku_apk_path()
    if not apk:
        raise RuntimeError(
            "Shizuku APK not found (pm path %s) — install Shizuku first"
            % SHIZUKU_PKG
        )
    os.makedirs(RISH_DIR, mode=0o755, exist_ok=True)
    os.makedirs(BIN, mode=0o755, exist_ok=True)
    dex_dest = os.path.join(RISH_DIR, DEX_NAME)
    with zipfile.ZipFile(apk, "r") as zf:
        try:
            data = zf.read("assets/" + DEX_NAME)
        except KeyError as e:
            raise RuntimeError(
                "Shizuku APK missing assets/%s" % DEX_NAME
            ) from e
    # Android 14+: app_process refuses writable dex — write then chmod 400.
    tmp = dex_dest + ".tmp"
    with open(tmp, "wb") as f:
        f.write(data)
    os.replace(tmp, dex_dest)
    os.chmod(dex_dest, 0o400)
    body = _WRAPPER_BODY.format(
        rish_dir=RISH_DIR, dex=DEX_NAME, pkg=SHIZUKU_PKG
    )
    with open(WRAPPER, "w") as f:
        f.write(body)
    os.chmod(WRAPPER, 0o755)
    return WRAPPER


def status() -> dict:
    return {
        "installed": installed(),
        "wrapper": WRAPPER if os.path.isfile(WRAPPER) else None,
        "dex": os.path.join(RISH_DIR, DEX_NAME)
        if os.path.isfile(os.path.join(RISH_DIR, DEX_NAME))
        else None,
        "apk": shizuku_apk_path(),
    }


def main(argv=None) -> int:
    argv = argv if argv is not None else sys.argv[1:]
    if not argv or argv[0] in ("-h", "--help"):
        sys.stderr.write("usage: stayturgid_rish.py install|status|which [--force]\n")
        return 2
    cmd = argv[0]
    force = "--force" in argv[1:]
    if cmd == "install":
        path = install(force=force)
        print("rish installed: %s" % path)
        return 0
    if cmd == "status":
        import json

        print(json.dumps(status(), indent=2))
        return 0 if installed() else 1
    if cmd == "which":
        if not installed():
            print("not installed", file=sys.stderr)
            return 1
        print(WRAPPER)
        return 0
    sys.stderr.write("unknown command %r\n" % cmd)
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
