appId: net.dinglisch.android.taskerm
---
# Check PROFILES tab
- tapOn:
    text: "PROFILES"
- takeScreenshot: /tmp/maestro_v1_profiles
- waitForAnimationToEnd:
    timeout: 2000

# Check TASKS tab
- tapOn:
    text: "TASKS"
- takeScreenshot: /tmp/maestro_v2_tasks
