---
- name: F-Droid repos (Neo Store)
  hosts: phones
  gather_facts: false
  vars:
    stayturgid_repo_root: "{{ playbook_dir }}/../.."
    target_device: "{{ inventory_hostname }}"
    stayturgid_fdroid_repos:
      - name: IzzyOnDroid
        address: https://apt.izzysoft.de/fdroid/repo
        fingerprint: 3BF0D6ABFEAE2F401707B6D966BE743BF0EEE49C2561B9BA39073711F628937A
  roles:
    - role: stayturgid.obtainium.obtainium_apps
    - role: stayturgid.fdroid.fdroid_repos
